### ISSUE TITLE
Modifying slide metadata

### ISSUE THREAD

**Issue by KShammout632** [openslide/openslide-python#103]
## Context

**Issue type**: Feature request 
**Operating system**: Windows 10 
**Platform**: 64-bit 
**OpenSlide Python version**: 1.1.1 
**OpenSlide version**: 3.4.1 
**Slide format**: tiff 

## Details
From what I gather, openslide is a reading and not a writing library, but I would like to be able to anonymize a slide by removing the label image from it. I can view the label image in openslide, but can't modify it. If this feature is not likely to be implemented, would it be possible to know how openslide is able to open a slide with an uncompressed size of 60GB without running out of memory? I have dug through the source code, but couldn't pinpoint the implementation to do that. Would be helpful if openslide also allowed modification of the slide and its metadata. Any information will help, thank you.

**Comment by bgilbert** [comment]
Yes, OpenSlide is a read-only library, and will not support modifying slide files.

Whole-slide images are designed to allow random access within the slide file.  OpenSlide loads the slide metadata into memory and then uses the metadata to read individual image tiles as needed.

[anonymize-slide](https://github.com/bgilbert/anonymize-slide) might be useful to you, or at least serve as a helpful starting point.
