### ISSUE TITLE
Read and process whole slide in python with Open slide

### ISSUE THREAD

**Issue by joelvis-maker** [openslide/openslide-python#104]
## Context
Issue type: Feature request
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide Python version** (`openslide.__version__`): Python version: 1.1.1
**OpenSlide version** (`openslide.__library_version__`): Python version: 1.1.1
**Slide format** (e.g. SVS, NDPI, MRXS): bif

## Details

I use python to read complete slides with Google Colab. I have several problems:

I can't find any books to properly learn openslide and its functions. To learn how to process whole slides, and print their label. Does a book or a complete document to get started with openslide exist?

When I try to deal with the image, google colab crashes. Then what I want to do is rework the images to make them usable, but I am not very familiar with openslide.

Here is the image I am using:

https://drive.google.com/file/d/1VNtW4A6mLCU5H4lc3FFeeJWYMf3ic3mi/view

Here is the image I would like to have:

https://drive.google.com/file/d/17XzwU71yUOUXPR-wLmmI9X1VL7DntWn1/view?usp=sharing

Here is an example of my code that crashes google colab:

    slide = ops.OpenSlide('/content/gdrive/My Drive/img/BI14N7185 (12).bif')
    print (slide.level_dimensions)
    ((65172, 130255), (32586, 65128), (16293, 32564), (8147, 16282), (4074, 8141), (2037, 4071), (1019, 2036), (510, 1018), (255, 509), (128, 255), (64, 128))
    
    
    [w, h] = slide.level_dimensions[0]
    print(w,h)
    
    simg = slide.get_thumbnail((w,h))
    plt.imshow(simg)
    plt.show()

**Comment by bgilbert** [comment]
OpenSlide C API documentation is [here](https://openslide.org/api/openslide_8h.html) and OpenSlide Python API documentation is [here](https://openslide.org/api/python/).  There's also other documentation on the [OpenSlide website](https://openslide.org/) that you might find useful.  If you want the slide label, check out the slide's associated images.

You're attempting to load the entire slide level 0 into memory, which for that slide requires more than 31 GiB of RAM.  You should read the slide in smaller chunks, or read a lower-resolution level.
