### ISSUE TITLE
Wants to know-how openslide create some extra image dimensions.

### ISSUE THREAD

**Issue by Yuvi-416** [openslide/openslide-python#107]
Hello there,

Can anybody explain how  openslide downsample the original pyramid (which has a 5 series in total) into 9 level_count or a 9 level_dimensions although image has just five series or five dimensions in real. How does openslide create some extra dimensions?
For an example:

![](https://aws1.discourse-cdn.com/business4/uploads/imagej/optimized/3X/f/a/fa29100eb2b111393f662a96dcfd4b5ff6a60be0_2_690x95.png)

Although image has just these five dimensions in real,
Image Width: 186496 Image Length: 36608
Image Width: 46624 Image Length: 9152
Image Width: 11656 Image Length: 2288
Image Width: 2914 Image Length: 572
Image Width: 728 Image Length: 143

I want to know how does openslide create missing dimensions.
Please insight me on this🙂

**Comment by bgilbert** [comment]
JPEG images can be efficiently downsampled while they're being decoded.  OpenSlide does this for Hamamatsu slides (only), since their zoom levels are sometimes far apart.  Slide levels are only synthesized if that level doesn't already exist in the file.
