### ISSUE TITLE
Convert a slide to PNG with Openslide

### ISSUE THREAD

**Issue by joelvis-maker** [openslide/openslide-python#108]
## Context

Issue type: Feature request
Operating system (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
Platform (e.g. 64-bit x86, 32-bit ARM): 64-bit
OpenSlide Python version (openslide.__version__): Python version: 1.1.1
OpenSlide version (openslide.__library_version__): Python version: 1.1.1
Slide format (e.g. SVS, NDPI, MRXS): bif

## Details

I'm importing a slide in .bif format and trying to convert the entire slide to png. But there is a duplicate of the slide in the png file. How do you import an entire slide and save in png format?

I am using google drive for programming and python 3

What I want is to automate the processing of the .biff to the png by saving the entire image.

my input :
https://drive.google.com/file/d/1IVzXnnZ5fmKg65Yf7rRNFG2I5yFap7PA/view?usp=sharing
    
    my code:
    
    slide = ops.OpenSlide('test.bif')
    
    level = 3
    downsample = int(slide.level_downsamples[level])
    width, height = slide.level_dimensions[level]
    read_size = 4096 
    # Calculate number of vertical and horizontal reads we'll need to take
    vertical_reads = ((height - 1) // read_size) + 1
    horizontal_reads = ((width - 1) // read_size) + 1
    
    # Storage for all of our reads
    all_imgs = []
    
    for v_read in range(vertical_reads):
        for h_read in range(horizontal_reads):
            img = slide.read_region(((h_read * read_size)*downsample, (v_read * read_size)*downsample), level, (read_size, read_size))
              
            img_array = np.asarray(img)
            all_imgs.append(img_array)       
          
    composite_image = np.zeros((vertical_reads * read_size, horizontal_reads * read_size, 4), dtype=np.uint8)
    
    for i in range(vertical_reads):
        for j in range(horizontal_reads):
              
            start_i = i * read_size
            end_i = start_i + read_size
              
            start_j = j * read_size
            end_j = start_j + read_size
              
            composite_image[start_i:end_i, start_j:end_j,:] = all_imgs[(i * horizontal_reads) + j]
    img = Image.fromarray(composite_image)
    
    
my current output:
https://drive.google.com/file/d/11BFTEj9yCtuMNQiEz1P7NULoqu3g7uc3/view?usp=sharing

**Comment by bgilbert** [comment]
We don't handle support requests in the OpenSlide Python issue tracker.  Please send your questions to the [openslide-users mailing list](https://lists.andrew.cmu.edu/mailman/listinfo/openslide-users/).

But you might want to check out `openslide-write-png`.
