### ISSUE TITLE
I would like to know how does openslide handle .scn extension wsi images.

### ISSUE THREAD

**Issue by Yuvi-416** [openslide/openslide-python#109]
Hi there,
I have downloaded some .scn images from here: http://openslide.cs.cmu.edu/download/openslide-testdata/Leica/
When I load these image (for example Leica-2.scn) using Openslide-python command, I can see that images has:
level_dimension: ((106259, 306939), (26565, 76735), (6642, 19184), (1661, 4796), (416, 1201), (104, 298))
Level-downsample: (1.0, 3.9999746623105956, 15.998891062171904, 63.98593267568448, 255.4999069285211, 1025.858899070728)

But when I load the same image with python-bioformats, It shows me that there are 27 series in that image.
So my questions is, how does openslide handle .scn images and how does 27 series images are converted to 6 series images as shown in level_dimension above.

Any suggestion.

**Comment by bgilbert** [comment]
Thanks for [sending](https://lists.andrew.cmu.edu/pipermail/openslide-users/2020-December/001602.html) your question to the mailing list; that's a better venue for it than the OpenSlide Python issue tracker.  I'll close this.
