### ISSUE TITLE
Version release

### ISSUE THREAD

**Issue by ernestoarbitrio** [openslide/openslide-python#113]
Hi,
   I was just wondering if there is a schedule for the next release of `openslide-python` that will include this fix https://github.com/openslide/openslide-python/pull/101 . This will help using this packed on windows and python 3.8 😄 .

Thanks

**Comment by bgilbert** [comment]
The issue will be addressed via documentation changes, and possibly a clearer error message if the OpenSlide DLL can't be found.  Those will make it into a release in due course, but you can already update your application to avoid the issue.  See https://github.com/openslide/openslide-python/issues/115#issuecomment-799025314 for details.
