### ISSUE TITLE
Change of behavior in DLL path searching in Python 3.8

### ISSUE THREAD

**Issue by CielAl** [openslide/openslide-python#115]
## Context
importing openslide-python in python >3.8

**Issue type** (bug report or feature request):  Bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
64-bit
**OpenSlide Python version** (`openslide.__version__`): 
1.1.2
**OpenSlide version** (`openslide.__library_version__`): 
3.4.1.0

## Details
If I understand it correctly, in python3.8, the behavior to search the DLLs might be different from previous distros (https://docs.python.org/3/library/os.html#os.add_dll_directory), which leads to exceptions like:

> FileNotFoundError: Could not find module 'libopenslide-0.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The same problem seems to be reported in https://github.com/openslide/openslide-python/issues/98 as well.

The error is not reproduced in the exact same environment but using python 3.7.

**Comment by CielAl** [comment]
@simo1427 's approach in issue: https://github.com/openslide/openslide-python/issues/98 appears to be one of the possible workarounds.

Either way, it seems like the library loading procedure for Windows in lowlevel.py should be adjusted corresponding to the update in the python distro.

**Comment by bgilbert** [comment]
Thanks for filing a new bug to highlight this issue.  If Python has decided to tighten the library loading rules [for security reasons](https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew), I don't think we should be defeating those changes.  So this might be better addressed with a documentation fix.

Does this work?
```python
import os
if hasattr(os, 'add_dll_directory'):
    with os.add_dll_directory(r'c:\path\to\openslide\directory'):
        import openslide
else:
    import openslide
```

**Comment by bgilbert** [comment]
On DLL load failure, we should probably detect that `os.add_dll_directory` exists and throw an exception mentioning it.

**Comment by bgilbert** [comment]
https://github.com/openslide/openslide-python/pull/156 fixes this by documenting the need for `os.add_dll_directory()` and adding some hints to the exception text if the DLL can't be found.  Thanks for the report!
