### ISSUE TITLE
height and width vs x_mpp, y_mpp

### ISSUE THREAD

**Issue by gabrieldernbach** [openslide/openslide-python#116]
Reading the API
https://openslide.org/api/python/

I find that the `slide.dimensions` property will yield a `(width, height)` tuple, which I understand as the number of pixels in the horizontal and vertical image directions (in that order).

In the standard property section the microns per pixel resolution is listed with  `openslide.PROPERTY_NAME_MPP_X` and Y respectively.

From cartesian coordinate conventions I assume that `x` is the first dimension (stored) and corresponds to the horizontal axis. Can you confirm that the `MPP_X` describes property of the `width` axis in the image dimensions?

I found image libraries do not necessarily agree on which dimension should be accessed first (x, y).

Thanks you for clarification.

**Comment by bgilbert** [comment]
Yes, `MPP_X` describes the horizontal (width) axis.
