### ISSUE TITLE
Do you know why I can't recognize the added environment variable? #2

### ISSUE THREAD

**Issue by bbhxwl** [openslide/openslide-python#118]
D:\Program Files (x86)\openslide-win64-20171122\bin
D:\Program Files (x86)\openslide-win64-20171122\lib

Environment variables add these two

**Comment by bgilbert** [comment]
Please send all support questions to the openslide-users mailing list, not the bug tracker.  You should provide much, much more information about your situation if you want anyone to be able to help you.
