### ISSUE TITLE
open ndpi file which image size > 4G(approximate value) will cause error

### ISSUE THREAD

**Issue by JiweiMaster** [openslide/openslide-python#120]
## Context

**Issue type** (bug repor): 
**Operating system** (ubuntu and windows): 
**Platform** (64-bit x86): 
**OpenSlide Python version** (`openslide.__version__: 1.1.2`): 
**OpenSlide version** (`openslide.__library_version__: 3.4.0`): 
**Slide format** (NDPI): 

## Details

open the ndpi image which image size  = 25491013632 pixels will cause the following error
`PIL.Image.DecompressionBombError: Image size (25491013632 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack`
so I add the following code
`from PIL import ImageFile,Image
Image.MAX_IMAGE_PIXELS = None`
finally the error changed:
`openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file`

and I can open the ndpi image with OpenScope software, so I think the image is effective

Some help will be appreciated
thk

**Comment by bgilbert** [comment]
Your slide file is not currently supported by OpenSlide.  Some NDPI slides are not, including large slide files (https://github.com/openslide/openslide/issues/174).  OpenSlide Python is trying to fall back to opening the file as a normal TIFF, and failing.
