### ISSUE TITLE
View miss classified patches on original .svs file

### ISSUE THREAD

**Issue by Nikhil-cyber-93** [openslide/openslide-python#121]
Hello everyone,

I am working on classification task of normal vs tumour on some medical images which are in .svs format. I have drawn patches of size 512 x 512 from a particular medical slide image using OpenSlide library. I trained mt machine learning classifier. After training, I got some miss-classified patches. Now I need to view these patches on the original slide so that we can understand which area of that slide is being miss classified more. Or I need to watch miss classified zone or pixels in original image. How to do it with Openslide?

**Comment by bgilbert** [comment]
I'd just use `read_region()` to get the pixels from the affected region, and then `save()` the resulting `PIL.Image` to a file.

**Comment by Nikhil-cyber-93** [comment]
@bgilbert,
Thanks for the response. Sorry to bother you again. I couldn't understand the solution as I am new to Openslide. I have used read_region() to extract patches and saved them in one folder. Then I feed these patches to a classifier and came to know that some patches are miss classified. Now, I want to view these miss-classified portion or pixels on original .svs file. I need to mark them with some colour I guess. So can you please elaborate your approach/solution ? It will be a great help. Thanks

**Comment by bgilbert** [comment]
OpenSlide is mostly just a library for reading pixels from slide files.  Once you have those pixels, what you do with them is up to you.  If you want to visualize an entire slide file and draw annotations on top, OpenSlide Python has some example web-based viewers which might be a useful starting point.   But they're examples, and not really part of the scope of OpenSlide itself.
