### ISSUE TITLE
What  image format dose openslide-python support？I hava tried tiff，tif etc，but they still raise this error

### ISSUE THREAD

**Issue by LIUZHENYU0609** [openslide/openslide-python#130]
## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide Python version** (`openslide.__version__`): 
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS):

**Comment by bgilbert** [comment]
See list at https://openslide.org/#about-openslide.
