### ISSUE TITLE
Need help! In image pyramid, is image of level=0 equal to scaning image from Aperio with most magnification?

### ISSUE THREAD

**Issue by huangjin520** [openslide/openslide-python#137]
## Details:
`Format: .svs`
`openslide-python`
if the slide is scanned in 20X resulation, we open the slide with openslide_python . Then ,i print the slide's properties, and i find the  
```
slide.level_downsamples = (1.0, 4.0001616525036034, 16.002643471213204)
slide..level_dimensions = ((50375, 47017), (12593, 11754), (3148, 2938))
```
I am stumble here , **because i don't konw level=0 belongs to 16x or 20x.**

**Comment by bgilbert** [comment]
Please send support requests to the openslide-users mailing list, not to the bug tracker.  But take a look at `slide.properties["openslide.objective-power"]`.
