### ISSUE TITLE
Unable to install openslide-python

### ISSUE THREAD

**Issue by davepruitt** [openslide/openslide-python#14]
When I do this: pip install openslide-python

It gives me an error during the install process:

"error: Unable to find vcvarsall.bat"

Suggestions?

**Comment by bgilbert** [comment]
What is your Python version and CPU architecture (x86 or x64)?

**Comment by davepruitt** [comment]
Python 3.5, x64

**Comment by bgilbert** [comment]
Okay, I need to get wheels uploaded for Python 3.5.  I'll work on that and get back to you.

**Comment by bgilbert** [comment]
I've uploaded a 64-bit wheel for Python 3.5, and am [having problems](https://sourceforge.net/p/pypi/support-requests/602/) getting PyPI to accept the 32-bit wheel.  In any event, for your purposes this should be working now; try again?

**Comment by bgilbert** [comment]
OpenSlide Python 1.1.1 has been uploaded to PyPI with wheels for Python 3.5.  Thanks for the report.
