### ISSUE TITLE
Want to rewrite in Java, need your help!

### ISSUE THREAD

**Issue by linruicheng1997** [openslide/openslide-python#145]
## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide Python version** (`openslide.__version__`): 
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details

Hello author, I am a beginner of OpenSeadragon. I see that there is a dzi file generated in your code, but it is not saved locally. How did you deal with it? Can you provide the design idea of the whole program, I want to use Java to reproduce your code, but I don't know much about your whole design idea.

**Comment by linruicheng1997** [comment]
Using Java to reproduce deepzoom_multiserver.py, can you share with me your overall design ideas? Many deepzoom examples on the Internet save the dzi file generated by WSI locally, which takes a lot of time and disk space, and does not conform to constants. Since seeing your example, I found that you can directly read the entire WSI and load it on demand. I am very eager to learn more about him. I hope you can provide me with a document or other things that you find useful. Thank you. Endless.

**Comment by bgilbert** [comment]
There is some documentation available on the [OpenSlide website](https://openslide.org), and the code is publicly available for inspection.  This issue tracker isn't intended for support requests, so I'll close.
