### ISSUE TITLE
How can I read .dat file by openslide?

### ISSUE THREAD

**Issue by yyn10152333** [openslide/openslide-python#149]
Hi there, 

I have WSIs in .dat format, and I found that they can be read as .mrxs with Slidedat.ini. But I don't know how to do this.
<img width="154" alt="image" src="https://user-images.githubusercontent.com/70582598/154952996-1f6964a7-d4fd-4fea-a11e-cc7c881cd066.png">
Does someone know?

Thank you very much.

**Comment by bgilbert** [comment]
You can't open the `.dat` files with OpenSlide directly.  Those files will generally be grouped together in a directory called, for example, `slide-x`.  That directory will be next to a file called `slide-x.mrxs`; open that file with OpenSlide instead.
