### ISSUE TITLE
Exporting DZI With tiles

### ISSUE THREAD

**Issue by hamza-arshad** [openslide/openslide-python#15]
I understand I can give .scn image to openslide and it will create in-memory dzi object. Can I export this object? so that I can use it with openseadragon to view.

**Comment by bgilbert** [comment]
You can get Deep Zoom XML with `DeepZoomGenerator.get_dzi()` and individual tiles with `DeepZoomGenerator.get_tile()`.  You can then write them to disk or send them over a network.  For sample tools that produce an on-disk directory tree or serve tiles to a web browser, see `deepzoom_tile.py` and `deepzoom_server.py` in the [examples/deepzoom](https://github.com/openslide/openslide-python/tree/master/examples/deepzoom) directory of the OpenSlide Python source distribution.

Please send usage questions to the [openslide-users mailing list](http://lists.andrew.cmu.edu/mailman/listinfo/openslide-users/).  Thanks!
