### ISSUE TITLE
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

### ISSUE THREAD

**Issue by lanfz2000** [openslide/openslide-python#153]
## Context
[G3_Mask.zip](https://github.com/openslide/openslide-python/files/8646990/G3_Mask.zip)
There is an error when using openslide to open a tif file.
But I cannot find out where is wrong.

code as:
`mask_slide = openslide.OpenSlide('G3_Mask.tif')`

`Traceback (most recent call last):
    raise OpenSlideUnsupportedFormatError(
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file` 

The file is in the zip. (only 2Mb)

**Comment by bgilbert** [comment]
This is not a tiled TIFF.  The OpenSlide generic TIFF driver [only supports tiled images](https://openslide.org/formats/generic-tiff/#detection).

**Comment by lanfz2000** [comment]
> This is not a tiled TIFF. The OpenSlide generic TIFF driver [only supports tiled images](https://openslide.org/formats/generic-tiff/#detection).

How can I transfer it to the type which can be opened by openslide. Could you give some suggestions?

**Comment by innocence0206** [comment]
> > This is not a tiled TIFF. The OpenSlide generic TIFF driver [only supports tiled images](https://openslide.org/formats/generic-tiff/#detection).
> 
> How can I transfer it to the type which can be opened by openslide. Could you give some suggestions?

I run into the same problem，have you solve it？
