### ISSUE TITLE
OSError: incompatible architecture (have 'arm64', need 'x86_64')

### ISSUE THREAD

**Issue by ryanreavette** [openslide/openslide-python#177]
I am trying to install OpenSlide on an Apple Silicon Mac.

Operating System: MacOS 12.4
Platform: 64 bit ARM

I tried installing as follows:

    brew install openslide
    python3 -m .venv venv
    source .venv/bin/activate
    pip3 install openslide-python

All worked. The error comes when I try the following in a python script:

    import openslide

I originally got the same error as in #146, so tried that solution:

    sudo ln -s /opt/homebrew/lib/libopenslide.dylib /usr/local/lib/libopenslide.dylib

I now get a new error:

    OSError: dlopen(/usr/local/lib/libopenslide.dylib, 0x0006): tried: '/usr/local/lib/libopenslide.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/opt/homebrew/Cellar/openslide/3.4.1_5/lib/libopenslide.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by bgilbert** [comment]
It looks as though your Python interpreter is built for x86_64 for some reason.  Are you using the Python interpreter shipped with the OS, or one from Homebrew, or did you get Python somewhere else?

**Comment by ryanreavette** [comment]
Fixing that solved it – thanks very much.
