### ISSUE TITLE
Can not import OpenSlideCache

### ISSUE THREAD

**Issue by zhangdan8962** [openslide/openslide-python#179]
## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
Ubuntu 20.04
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
64-bit
**OpenSlide Python version** (`openslide.__version__`): 
1.1.1
**OpenSlide version** (`openslide.__library_version__`): 
3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): 
TIFF

## Details

I am trying to run deepzoom_multiserver.py but get the following error:
`Traceback (most recent call last):
  File "deepzoom_multiserver.py", line 47, in <module>
    from openslide import OpenSlide, OpenSlideCache, OpenSlideError, OpenSlideVersionError
ImportError: cannot import name 'OpenSlideCache' from 'openslide' (/usr/lib/python3/dist-packages/openslide/__init__.py)
`

**Comment by bgilbert** [comment]
It appears you're using OpenSlide Python 1.1.1 with a `deepzoom_multiserver.py` from OpenSlide Python 1.2.0.  The newer `deepzoom_multiserver.py` uses functionality that isn't available in older versions of OpenSlide Python.
