### ISSUE TITLE
How can I extract patches from the original whole slide images according to my predefined magnification times?

### ISSUE THREAD

**Issue by brisker** [openslide/openslide-python#18]
I have used the python wrapper of openslide and got several folders containing lots of patch images of WSI ,but I can not figure out what magnification times they belong to. Could you please tell me how to solve this problem? 

![image](https://cloud.githubusercontent.com/assets/13804492/16525685/222c1aa8-3fe0-11e6-95e6-31d14827ecf7.png)
![image](https://cloud.githubusercontent.com/assets/13804492/16525700/360ea52c-3fe0-11e6-8793-21e34b15260c.png)

**Comment by bgilbert** [comment]
Hi @brisker, your screenshot shows the output of `deepzoom_tile.py`, which produces Deep Zoom pyramids as output.  The highest-numbered directory corresponds to level 0 of the slide (that is, full resolution), and each next lower-numbered directory is a factor of two reduction from the previous one.

To answer the question in the issue title, OpenSlide exposes slide "levels" corresponding to the resolutions stored in the slide file.  From the Python API, you can find out the (reported) resolution of level 0 in microns per pixel from `OpenSlide.properties["openslide.mpp-x"]` and `...mpp-y...`, and the downsamples of each level relative to level 0 from `OpenSlide.downsamples`.  You then need to do some math (the `OpenSlide.get_best_level_for_downsample()` method can do part of this) to figure out which level to read and how much additional downscaling to do on the returned images.

In the future, please send your support questions to the openslide-users mailing list, not to the issue tracker.
