### ISSUE TITLE
Artifact

### ISSUE THREAD

**Issue by 464hee** [openslide/openslide-python#185]
## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
linux 64
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide Python version** (`openslide.__version__`): 
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS): 
tif
## Details

There are obvious boundary lines when reading tif, but it is normal to use tiffslide to read

**Comment by 464hee** [comment]
[png.zip](https://github.com/openslide/openslide-python/files/10049607/png.zip)

**Comment by 464hee** [comment]
name_i = 'test.tif'
mask_path = '/media/totem_disk/totem/hebingdou/0_SEG/slide_predict/tmp_test/output/'+name_i
print(name_i)
for mask_level in range(2,5):
    print('----------------------' + str(mask_level) + '-----------------------')
    open_slide = Slide(mask_path)
    open_slide_lv0_wh = open_slide.get_level_dimension(mask_level)
    # seg_result_0 = np.array(open_slide.get_thumb(mask_level))[:,:,0]
    seg_result_0  = np.array(open_slide.read_region((0,0), mask_level ,open_slide_lv0_wh))[:,:,0]
    os.makedirs('./output/'+name_i.replace('.tif','')+'/', exist_ok=True)
    visual_1(seg_result_0,'./output/'+name_i.replace('.tif','')+'/'+str(mask_level)+'_open_slide.png')

    tiff_slide = TiffSlide(mask_path)
    lv0_hw = tiff_slide.level_dimensions[mask_level][::-1]
    seg_result_2 = tiff_slide.read_region((0, 0), mask_level, lv0_hw[::-1], as_array=True)[:, :, 0]

    visual_1(seg_result_2,'./output/'+name_i.replace('.tif','')+'/'+str(mask_level)+'_tiff_slide.png')

**Comment by 464hee** [comment]
`name_i = 'test.tif'
mask_path = '/media/totem_disk/totem/hebingdou/0_SEG/slide_predict/tmp_test/output/'+name_i
print(name_i)
for mask_level in range(2,5):
    print('----------------------' + str(mask_level) + '-----------------------')
    open_slide = Slide(mask_path)
    open_slide_lv0_wh = open_slide.get_level_dimension(mask_level)
    # seg_result_0 = np.array(open_slide.get_thumb(mask_level))[:,:,0]
    seg_result_0  = np.array(open_slide.read_region((0,0), mask_level ,open_slide_lv0_wh))[:,:,0]
    os.makedirs('./output/'+name_i.replace('.tif','')+'/', exist_ok=True)
    visual_1(seg_result_0,'./output/'+name_i.replace('.tif','')+'/'+str(mask_level)+'_open_slide.png')

    tiff_slide = TiffSlide(mask_path)
    lv0_hw = tiff_slide.level_dimensions[mask_level][::-1]
    seg_result_2 = tiff_slide.read_region((0, 0), mask_level, lv0_hw[::-1], as_array=True)[:, :, 0]

    visual_1(seg_result_2,'./output/'+name_i.replace('.tif','')+'/'+str(mask_level)+'_tiff_slide.png')
`

**Comment by 464hee** [comment]
`name_i = 'test.tif'
mask_path = '/media/totem_disk/totem/hebingdou/0_SEG/slide_predict/tmp_test/output/'+name_i
print(name_i)
for mask_level in range(2,5):
    print('----------------------' + str(mask_level) + '-----------------------')
    open_slide = Slide(mask_path)
    open_slide_lv0_wh = open_slide.get_level_dimension(mask_level)
    # seg_result_0 = np.array(open_slide.get_thumb(mask_level))[:,:,0]
    seg_result_0  = np.array(open_slide.read_region((0,0), mask_level ,open_slide_lv0_wh))[:,:,0]
    os.makedirs('./output/'+name_i.replace('.tif','')+'/', exist_ok=True)
    visual_1(seg_result_0,'./output/'+name_i.replace('.tif','')+'/'+str(mask_level)+'_open_slide.png')

    tiff_slide = TiffSlide(mask_path)
    lv0_hw = tiff_slide.level_dimensions[mask_level][::-1]
    seg_result_2 = tiff_slide.read_region((0, 0), mask_level, lv0_hw[::-1], as_array=True)[:, :, 0]

    visual_1(seg_result_2,'./output/'+name_i.replace('.tif','')+'/'+str(mask_level)+'_tiff_slide.png')
`

**Comment by 464hee** [comment]
[png_and_code.zip](https://github.com/openslide/openslide-python/files/10049625/png_and_code.zip)

**Comment by 464hee** [comment]
Can you tell me what causes this exception on the openslide?

**Comment by 464hee** [comment]
I use Ubuntu 20.04,  openslide-python==1.1.2

**Comment by 464hee** [comment]
@bgilbert Look forward to your reply

**Comment by 464hee** [comment]
[png_and_code.zip](https://github.com/openslide/openslide-python/files/10049795/png_and_code.zip)

**Comment by bgilbert** [comment]
If I'm understanding your code and output correctly, you're expecting individual pixels to have specific hardcoded color values, but are seeing variations at the tile boundaries of downsampled levels.  That occurs because of the compositing which occurs at tile boundaries, and isn't too surprising.  OpenSlide doesn't guarantee that its output will be pixel-for-pixel identical to output produced by other software.
