### ISSUE TITLE
Edit .svs Aperio metadata with openslide

### ISSUE THREAD

**Issue by chalbiophysics** [openslide/openslide-python#186]
Hello !

Thank you for this great package !

## Context

**Issue type** (bug report or feature request): Is it possible to edit metadata in order to anonymize files ?
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10):  windows 10 family 
**Platform** (e.g. 64-bit x86, 32-bit ARM):  64 bit x 86
**OpenSlide Python version** (`openslide.__version__`): 1.2
**OpenSlide version** (`openslide.__library_version__`): 2022-11-11
**Slide format** (e.g. SVS, NDPI, MRXS): svs

## Details
With openslide package, I realized that data  are stored in aperio svs metadata, especially in the "filename". Is it possible with openslide to edit these metadata with openslide ? Or should I use another package ? 

Please, could you let me know if you have already faced this issue ?

Kindly

**Comment by bgilbert** [comment]
OpenSlide doesn't support modifying slide files.  You might want to check out [anonymize-slide](https://github.com/bgilbert/anonymize-slide) (which is unmaintained) or one of its forks.
