### ISSUE TITLE
Precompiled wheels for all operating systems

### ISSUE THREAD

**Issue by andreped** [openslide/openslide-python#187]
## Context

**Issue type** (bug report or feature request): 
There are various situations where building the package might fail. For instance on Windows, if VS Build Tools are not available. I see that this has been handled by building precompiled wheels for Windows specifically (see [here](https://github.com/openslide/openslide-python/releases/tag/v1.2.0)). However, depending on the end-user's settings, it may happen that the user is unable to build themselves, even on Ubuntu, during installation.

I therefore, believe it would be more optimal if we build wheels for all relevant operating systems and python versions, which should remove this issue.

That is quite easy to do as we only need to modify the workflow to do that:
https://github.com/openslide/openslide-python/blob/main/.github/workflows/python.yml

## Details

This was recently a problem when trying to install [MONAI Label](https://github.com/Project-MONAI/MONAILabel) on a client machine which did not have install `python dev tools` which resulted in `python setup.py install` failing for `openslide-python`. This will no longer be a problem if precompiled wheels are provided. I believe the MONAI Label team would be very interested in this (@diazandr3s).

If this is of interest, shall I make a PR to add support for various relevant operating systems and specific python versions?

**Comment by bgilbert** [comment]
xref #126 and #144.  If there's a relatively clean way to do this within GitHub Actions, a PR would be great.  Thanks!

**Comment by andreped** [comment]
> xref #126 and #144. If there's a relatively clean way to do this within GitHub Actions, a PR would be great. Thanks!

@bgilbert I can make an attempt later today and make a PR.

**Comment by andreped** [comment]
@bgilbert Made a PR which resolves this issue: https://github.com/openslide/openslide-python/pull/188

**Comment by bgilbert** [comment]
Yup, the wheels built by that PR failed to load on older Linux versions, which seemed to defeat the point.  As I understand it, we'd need to build in a [special container](https://github.com/pypa/manylinux), but that should be doable.

There are two separate questions: whether to build OpenSlide Python wheels for Linux and macOS, and whether to bundle OpenSlide (the actual C library) into those wheels.  I'm in favor of the former, but the latter is complex (OpenSlide has a lot of dependencies) and I'd consider it out of scope.

**Comment by andreped** [comment]
> Yup, the wheels built by that PR failed to load on older Linux versions

What we often do is to build on the oldest relevant Linux version, as python packages _tend to be_ forward compatible on Ubuntu. However, it is true that there is no guarantee. Manylinux solution might be the best fit.

However, I see that there exists an Action that can be used for exactly this purpose:
https://github.com/marketplace/actions/python-wheels-manylinux-build

**Comment by bgilbert** [comment]
Yes, please do.  I'd prefer to use explicit build steps rather than having the Action do it for us, but if that turns out to be too complex, the Action could be a reasonable alternative.
