### ISSUE TITLE
Possible memory leak with read_region

### ISSUE THREAD

**Issue by brendanofallon** [openslide/openslide-python#195]
### Operating system

MacOS 12.2

### Platform

Apple silicon

### OpenSlide Python version

1.2.0

### OpenSlide version

3.4.1

### Slide format

NDPI

### Issue details

I'm calling `slide.read_region(location, level (width, height))` inside a loop to generate small tiles spanning a large slide image. Each region is relatively small, about 1000x1000. For each region I compute a value (currently, just the mean) and then discard the data.  When doing this system memory usage (as reported by the built-in ActivityMonitor) increases linearly with time, using > 10Gb after a few minutes and performance becomes very poor across the whole OS, at which point I typically force the application to stop. 
 Not sure whats going on here - perhaps there's a caching mechanism with a too-large maximum size? Or just a plain old memory leak? Or maybe I'm doing something wrong and need to signal to openslide that it can reclaim the memory after a call to read_region? 
 Any advice or opinions?
 Thank you!

**Comment by bgilbert** [comment]
That shouldn't be happening.  Could you post a script that reproduces the issue?

**Comment by brendanofallon** [comment]
Apologies - this was definite user error on my part. I don't think there's an issue with openslide
