### ISSUE TITLE
Give a demo about how to use deepzoom

### ISSUE THREAD

**Issue by SCP-173-cool** [openslide/openslide-python#20]
I appreciate this HUB and it will be better if you give us a demo about how to use deepzoom with openslide

**Comment by bgilbert** [comment]
Have you looked at the [examples/deepzoom](https://github.com/openslide/openslide-python/tree/master/examples/deepzoom) directory?

**Comment by yeshbhosale** [comment]
I think he means to say make your documentation more properly, who have written all the definitions only, it would be great if you can add examples on each definitions.

**Comment by bgilbert** [comment]
@yeshbhosale I don't think adding `dz.get_tile(10, (0, 0))` or `osr.read_region((0, 0), 0, (1000, 1000))` would be very useful.  If someone would like to write a tutorial, though, that'd be great!  I'd be happy to provide feedback.

@SCP-173-cool Is there something in particular that seems unclear?

**Comment by SCP-173-cool** [comment]
@yeshbhosale is right! 
@bgilbert Well, I have taken part in the Camelyon2017 competition, which is a deep learning research competition based on the large datasets WSI(*.tiff).
I  think it will be better if I make a demo after using the BIG OPENSLIDE, and I'll push it to you.

**Comment by bgilbert** [comment]
@SCP-173-cool Sounds good!

**Comment by bgilbert** [comment]
The existing docs cover the entire API, and we also ship several pieces of example code.  Since the reporter didn't end up contributing a tutorial, I'll close this out.
