### ISSUE TITLE
openslide can not read a file with chinese path 

### ISSUE THREAD

**Issue by EachenL** [openslide/openslide-python#202]
### Operating system

windows10

### Platform

64-bit x86

### OpenSlide Python version

1.2.0

### OpenSlide version

3.4.1

### Slide format

ndpi

### Issue details

I can not use openslide to create a object Openslide about ndpi file with a chinese path, how can i deal with it?

**Comment by bgilbert** [comment]
This is fixed in the development version of OpenSlide.  Try using a [nightly build](https://openslide.org/builds/windows/) of the Windows binaries.

**Comment by EachenL** [comment]
Thanks
