### ISSUE TITLE
get_thumbnail bug report

### ISSUE THREAD

**Issue by 918938301** [openslide/openslide-python#204]
### Operating system

Ubuntu 16.04

### Platform

64-bit X86

### OpenSlide Python version

1.2.0

### OpenSlide version

3.4.0

### Slide format

TIFF

### Issue details

I use slide.get_thumbnail  on same size slide
but the thumbnail size is different

`slide_path = '/home/amax/tumor_009.tif'
truth_path = '/home/amax/d.tif'

slide = openslide.open_slide(slide_path)
truth = openslide.open_slide(truth_path)

print("Original Slide dimensions %dx%d" % slide.dimensions)
print("Original Truth dimensions %dx%d" % truth.dimensions)
print( slide.dimensions[0] / 256,slide.dimensions[1] / 256)
print( truth.dimensions[0] / 256 , truth.dimensions[1] / 256)`

Original Slide dimensions 97792x217088
Original Truth dimensions 97792x217088
382.0 848.0
382.0 848.0

but when I 
`thumbnail = slide.get_thumbnail((slide.dimensions[0] / 256, slide.dimensions[1] / 256))

thumbnail_truth = truth.get_thumbnail((truth.dimensions[0] / 256, truth.dimensions[1] / 256)) 

print(thumbnail.size)
print(thumbnail_truth.size)`

the size is different

(382, 764)
(382, 848)

**Comment by bgilbert** [comment]
What are the values of `slide.level_dimensions` and `truth.level_dimensions`?

**Comment by 918938301** [comment]
`import multiresolutionimageinterface as mir
reader = mir.MultiResolutionImageReader()
mr_image = reader.open('camelyon17/centre_0/patient_010_node_4.tif')
annotation_list = mir.AnnotationList()
xml_repository = mir.XmlRepository(annotation_list)
xml_repository.setSource('camelyon17/centre_0/patient_010_node_4.xml')
xml_repository.load()
annotation_mask = mir.AnnotationToMask()
camelyon17_type_mask = True
label_map = {'metastases': 1, 'normal': 2} if camelyon17_type_mask else {'_0': 1, '_1': 1, '_2': 0}
conversion_order = ['metastases', 'normal'] if camelyon17_type_mask else  ['_0', '_1', '_2']
annotation_mask.convert(annotation_list, output_path, mr_image.getDimensions(), mr_image.getSpacing(), label_map, conversion_order)`

I just use the offical demo of camelyon17 to get the truth mask, but the level_dimension between mask and the WSI is different, what should I do

**Comment by bgilbert** [comment]
You should ask the authors of the software that's generating the mask.  If two slides have downsampled levels with different aspect ratios, `get_thumbnail()` will also produce thumbnails with different aspect ratios.
