### ISSUE TITLE
miniconda & openslide-python; LIBFFI_BASE_7.0 

### ISSUE THREAD

**Issue by jonghyunlee1993** [openslide/openslide-python#205]
### Operating system

Linux 20.04

### Platform

64bit X86

### OpenSlide Python version

latest

### OpenSlide version

latest

### Slide format

NA

### Issue details

There is an unknown cause for an issue encountered while using openslide-python within a miniconda environment. The error message received is as follows:

`ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0`

Fortunately, I found a workaround for this problem in the following post:
https://blog.csdn.net/qq_38606680/article/details/129118491

The post is written in Chinese, but you can use a translator to understand it.

I would like to know if this issue can be resolved on the openslide-python side or if it should be brought to the attention of the miniconda team.

I truly appreciate the efforts put into developing this library. Thank you.

**Comment by bgilbert** [comment]
Thanks for the report.  This is an Anaconda issue: Anaconda shouldn't be mixing OS libraries with its own incompatible versions.  Please bring it to the attention of the Anaconda team.
