### ISSUE TITLE
WSIs appear dark black when I convert SVS files to 10x or lower scale factor 

### ISSUE THREAD

**Issue by monjoybme** [openslide/openslide-python#206]
### Operating system

Linux

### Platform

x86_64

### OpenSlide Python version

1.1.2

### OpenSlide version

3.4.1

### Slide format

SVS

### Issue details

Hi,

Some sections of the WSIs appear dark black when I convert SVS files to 10x or lower scale factor (some times even 20x or more) images [see attached sample]. I am not experiencing this issue with all images, but I believe it occurs when the SVS image size is large. When I increase the scale factor, I  have no problems. Do you have any solutions for this?

<img width="497" alt="Screenshot 2023-06-15 at 2 11 23 PM" src="https://github.com/openslide/openslide-python/assets/17875749/6a45edc9-5f1d-41fa-91ca-e187183b1936">

**Comment by bgilbert** [comment]
This is probably https://github.com/openslide/openslide/issues/278.  What Linux distribution and version are you using?

**Comment by monjoybme** [comment]
@bgilbert I am using `Centos 7, Architecture: x86_64, CPU op-mode(s):32-bit, 64-bit`.  I installed `conda install pixman=0.36.0`, but the issue doesn't solve.

**Comment by bgilbert** [comment]
I don't know Conda.  Is it possible that 0.38.0 is installed in parallel, and is still being used?  I'd recommend making sure that 0.38 is uninstalled.  The copy shipped natively in CentOS 7 doesn't have this issue, so the Conda copy is likely the problem.

**Comment by monjoybme** [comment]
@bgilbert This is not clear to me if `pixman` part of `Centos` or `OpenSlide`. I tired the approach mentioned [here ](https://github.com/TissueImageAnalytics/tiatoolbox/issues/133), but it didn't work.

**Comment by monjoybme** [comment]
> @bgilbert This is not clear to me if `pixman` part of `Centos` or `OpenSlide`. I also tired the approach mentioned [here ](https://github.com/TissueImageAnalytics/tiatoolbox/issues/133), but it didn't work.

Got it! It is a part of` Openslide`.  Now installing Openslide from the beginning.  Now I have`pixman-0.40.0`. Keep you posted. Thanks!

**Comment by monjoybme** [comment]
@bgilbert My problem has been resolved. I established a fresh conda environment and installed the most recent version of `Openslide-python`. I checked the `pixman` version, which was `0.40.0`, during the `Openslide` installation. `Pixman` did not work when I installed it individually. Hence, a fresh installation of `OpenSlide` is advised.  Thanks a lot for your help and guidance!
