### ISSUE TITLE
openslide acting different in python 2.7.10 and 2.7.6

### ISSUE THREAD

**Issue by yeshbhosale** [openslide/openslide-python#21]
## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide Python version** (`openslide.__version__`): 
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details

So i have a tiff image and am opening this image into level 6 on openslide but the width and height are different in python 2.7.10 and 2.7.6

Here is the code

        tumor_file = openslide.OpenSlide(tumor_img) 
        region_x, region_y = tumor_file.level_dimensions[6]

on python 2.7.10 region_x , region_y = 1472 1120
on python 2.7.6 region_x, region _y = 1536, 1536

**Comment by bgilbert** [comment]
Before I can look at your problem, I'll need the information from the form you deleted.  Please go back and fill out the form.  Be sure to obtain the OpenSlide and OpenSlide Python versions on both Python 2.7.6 and Python 2.7.10.

**Comment by yeshbhosale** [comment]
which form?

**Comment by bgilbert** [comment]
The one labeled **Context** at the top of the bug report.

**Comment by bgilbert** [comment]
I'll go ahead and close for now.  Feel free to reopen once you can provide the requested information.
