### ISSUE TITLE
How to force openslide to open a file as specific format?

### ISSUE THREAD

**Issue by shivamkalra** [openslide/openslide-python#22]
## Context

**Issue type**: Question 
**Operating system**: Arch Linux 
**Platform**: 64-Bit x86 
**OpenSlide Python version**: Latest 
**OpenSlide version**: Latest

## Details
I've image that behaves just like aperio format. How can I force openslide library to read it as aperio image instead of generic tiff?

**Comment by bgilbert** [comment]
OpenSlide will only read a file as Aperio if it [detects that it is an Aperio slide](http://openslide.org/formats/aperio/#detection).  There is no mechanism to override the detector.  If you want to see why the Aperio detector is rejecting your slide, set the `OPENSLIDE_DEBUG` environment variable to `detection`, try opening the file, and then check stderr.

If your file is produced by custom code for your own use, the easiest fix is probably to modify the generated file to conform to OpenSlide's detection rules.  However, if your file is produced for general use (for example, by a slide scanner, or by general-purpose analysis software), please file a bug in OpenSlide.  We may want to modify the format detector to support this type of file.

**Comment by shivamkalra** [comment]
Thanks for quick response. I end up in changing the aperio's detection code in libpenslide to satisfy my particular case.
