### ISSUE TITLE
"openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file" for DICOM image

### ISSUE THREAD

**Issue by markemus** [openslide/openslide-python#226]
### Operating system

Ubuntu

### Platform

64-bit x86

### OpenSlide Python version

1.3.0

### OpenSlide version

3.4.1

### Slide format

DCM

### Issue details

I'm getting this error when trying to read the [3DHISTECH-1.zip](https://openslide.cs.cmu.edu/download/openslide-testdata/DICOM/3DHISTECH-1.zip) DICOM example file. It's also occurring with my own dicom images. I tested openslide-python installed through both pip and conda.

```
>>> path = "Downloads/3d_hist_dicom/000001.dcm"
>>> import openslide
>>> openslide.OpenSlide(path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/creach2/miniconda3/envs/dicomizer/lib/python3.11/site-packages/openslide/__init__.py", line 179, in __init__
    self._osr = lowlevel.open(str(filename))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/creach2/miniconda3/envs/dicomizer/lib/python3.11/site-packages/openslide/lowlevel.py", line 203, in _check_open
    raise OpenSlideUnsupportedFormatError("Unsupported or missing image file")
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file```

**Comment by bgilbert** [comment]
OpenSlide 3.4.1 does not support DICOM.  Please try installing OpenSlide from Git, or you can wait a week or so for the next OpenSlide release.
