### ISSUE TITLE
No DICOM support in Anaconda version of openslide-python 1.3.1

### ISSUE THREAD

**Issue by markemus** [openslide/openslide-python#233]
### Operating system

Ubuntu

### Platform

64-bit x86

### OpenSlide Python version

1.3.1

### OpenSlide version

unknown

### Slide format

DCM

### Issue details

I installed openslide-python using `conda install -c conda-forge openslide-python`. I get `openslide.lowlevel.OpenSlideUnsupportedFormatError` with:

```>>> import openslide                                                            
>>> openslide.OpenSlide("000001.dcm")                                           
```
when trying to import the first DICOM image from the 3DHISTECH example file.

**Comment by bgilbert** [comment]
OpenSlide Python is just a wrapper around OpenSlide.  DICOM support requires OpenSlide 4.0.0, conda-forge [hasn't updated to 4.0.0 yet](https://github.com/conda-forge/openslide-feedstock), and the update will require [some effort](https://github.com/conda-forge/openslide-feedstock/pull/20#issuecomment-1781623442).  If you'd like to work on updating the package, I'm sure the recipe maintainers would appreciate the help!
