### ISSUE TITLE
Open file slow in a docker container 

### ISSUE THREAD

**Issue by TaylorHere** [openslide/openslide-python#25]
## Context

**Issue type** (bug report or feature request): 
report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
Mac OS 10.03
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
64-bit x86
**OpenSlide Python version** (`openslide.__version__`): 
1.1.1
**OpenSlide version** (`openslide.__library_version__`): 
3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): 
TIFF
## Details
from openslide import OpenSlide

slide = OpenSlide("/path/to/slide")
this line of code works fine and fast on my mac,
but when I try to let that code work in a docker container which based on Ubuntu 14.04
and the file comes from a docker volume, the OpenSlide operation becomes very slow. 
I'm now trying to change the docker's storage driver, hope that can help.

**Comment by bgilbert** [comment]
Hi @TaylorHere, how slow is "very slow"?  Does OpenSlide seem slower than other I/O-intensive programs in the same configuration?  Unless the problem is with OpenSlide in particular, there's not a lot we can do about the performance of Docker's storage drivers.

**Comment by bgilbert** [comment]
Closing due to lack of response.  If you're still seeing this issue, feel free to reopen.
