### ISSUE TITLE
a  bug of mrxs

### ISSUE THREAD

**Issue by Yuan1z0825** [openslide/openslide-python#255]
### Operating system

Windows 11

### Platform

64-bit

### OpenSlide Python version

3.10

### OpenSlide version

1.3.1

### Slide format

MRXS

### Issue details

Reading mrxs files with openslide has a lot of black backgrounds, and the real organization is small why?

**Comment by Yuan1z0825** [comment]
![image](https://github.com/openslide/openslide-python/assets/140061814/265ebacb-eb6e-4247-8ca8-f286ccf93aa7)

**Comment by bgilbert** [comment]
Those aren't black pixels, they're transparent pixels.  Check the alpha channel.

OpenSlide uses the coordinate plane of the MRXS file, which covers the entire scan area.  The `openslide.bounds-*` [properties](https://openslide.org/docs/properties/) define a minimal bounding box around the opaque pixels.

**Comment by Yuan1z0825** [comment]
> Those aren't black pixels, they're transparent pixels. Check the alpha channel.
> 
> OpenSlide uses the coordinate plane of the MRXS file, which covers the entire scan area. The `openslide.bounds-*` [properties](https://openslide.org/docs/properties/) define a minimal bounding box around the opaque pixels.

Need to specify their own? I want an automatic method

**Comment by Yuan1z0825** [comment]
exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-f33051fe297f>", line 1, in <module>
    slide.bounds-x
AttributeError: 'OpenSlide' object has no attribute 'bounds'

**Comment by bgilbert** [comment]
OpenSlide properties are stored in `slide.properties`.  Read the bounds properties and use them to select the pixels to read.

**Comment by Yuan1z0825** [comment]
fine， I find it!
