### ISSUE TITLE
Streamlining installation on Linux/MacOS

### ISSUE THREAD

**Issue by ciroraggio** [openslide/openslide-python#256]
### Operating system

Linux/MacOS

### Platform

64-bit

### OpenSlide Python version

1.3.1

### OpenSlide version

N.A.

### Slide format

N.A.

### Issue details

Thanks for your work! 
I had a problem trying to install: `monai[all]` on my system (Ubuntu 22.04) without a compiler. 

After checking on PyPI [^1]  we realised that no wheels are provided for Linux and MacOS, so there is no way to install it.
It has also been discussed here  [^2] previously.
It would be ideal to also provide wheels for Linux and MacOS so that even those without developer experience can easily install it. 

To help @jcfr mentioned that updating openslide-python build system based on template available here would help with that: https://learn.scientific-python.org/development/guides/packaging-compiled/ 

[^1]: https://pypi.org/project/openslide-python/#files
[^2]:https://discourse.slicer.org/t/installing-openslide-python/24187

**Comment by bgilbert** [comment]
Support for building Linux and macOS wheels was added in #237, and OpenSlide Python 1.4.0 will include wheels for all three platforms.  Thanks for the report!
