### ISSUE TITLE
Openslide can't find my dylib files

### ISSUE THREAD

**Issue by aaljuhani** [openslide/openslide-python#27]
## Context

**Issue type** (bug report or feature request): 
**Operating system**  Mac OS 10.12
**Platform** 64-bit x86
**OpenSlide Python version** (`openslide.__version__`): 
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details
I am working on installing openslide on my Mac OS but can't get it to work. 
I am facing this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python2.7/site-packages/openslide/__init__.py", line 29, in <module>
    from openslide import lowlevel
  File ".../lib/python2.7/site-packages/openslide/lowlevel.py", line 55, in <module>
    "Is OpenSlide installed?")
ImportError: Couldn't locate OpenSlide dylib.  Is OpenSlide installed?
```

openslide is already installed and I can view it under lib/python2.7/site-packages 

Please advise.

Thanks

**Comment by bgilbert** [comment]
`libopenslide.0.dylib` needs to be installed in the dyld search path, not the Python site-packages directory.  How did you install OpenSlide?

**Comment by alisalub** [comment]
Hi,
I have a similar problem. I installed the OpenSlide wheel using `pip`, as instructed, but I'm receiving the same error.  When I write`import openslide` I receive the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alisa/Downloads/openslide-python-master/openslide/__init__.py", line 29, in <module>
    from openslide import lowlevel
  File "/home/alisa/Downloads/openslide-python-master/openslide/lowlevel.py", line 58, in <module>
    _lib = cdll.LoadLibrary('libopenslide.so.0')
  File "/opt/anaconda/anaconda2/envs/oslide/lib/python3.5/ctypes/__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "/opt/anaconda/anaconda2/envs/oslide/lib/python3.5/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

```
Installation using `python setup.py install`, as written in the README.md, didn't help as well. Any assistance would be appreciated. I tried both Python 3.5 and 3.6 on a Linux.

Alisa.

**Comment by bgilbert** [comment]
@alisalub Same question for you: how did you install OpenSlide?  If you installed from source, then most likely the install directory is not in your system's library search path.

**Comment by alisalub** [comment]
Hi @bgilbert,

I installed `openslide` using both suggested ways - `pip` and from source, and they both didn't work. I tried reinstalling from source just now, with your suggested `export` step, but I received the same error.

**Comment by alisalub** [comment]
Hi @bgilbert, I tried reinstalling using `yum` and the import works flawlessly. I have another issue with `libtiff`, but I'll open a new issue for it :)

Thanks.

**Comment by bgilbert** [comment]
@alisalub Glad you got it working.

@aaljuhani This is likely to be a problem with your installation, so I'll close.  If you're still seeing this with OpenSlide installed in your library search path, please reopen.

**Comment by shrutikannan** [comment]
Hi, I am facing the same issue. I tried installing using pip, and am getting the same error. I am not able to follow what you mean by : 

> If you're still seeing this with OpenSlide installed in your library search path

 What am I supposed to look for, and where?
Thanks!

**Comment by bgilbert** [comment]
@shrutikannan What OS are you using?  How did you install OpenSlide?

**Comment by clementgr** [comment]
hi, I am trying to install openslide-python 1.1.1 on Mac OS 10.14.5 (in a virtualenv environment) with the command :

`pip install openslide-python`

I am facing this error when typing `import openslide` in a python shell :

`Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/openslide/lowlevel.py", line 44, in <module>
    _lib = cdll.LoadLibrary('libopenslide.0.dylib')
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libopenslide.0.dylib, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/site-packages/openslide/__init__.py", line 29, in <module>
    from openslide import lowlevel
  File ".../lib/python3.6/site-packages/openslide/lowlevel.py", line 55, in <module>
    "Is OpenSlide installed?")
ImportError: Couldn't locate OpenSlide dylib.  Is OpenSlide installed?`

Please advise.

Thanks

**Comment by bgilbert** [comment]
OpenSlide Python requires OpenSlide.  After running `pip install openslide-python`, you must also install OpenSlide; on a Mac this is best done using MacPorts or Homebrew.  Sample commands are available on the [download page](https://openslide.org/download/#distribution-packages).

Locking this issue to avoid accumulating further support requests here.
