### ISSUE TITLE
Open .scn file - libtiff is unrecognized

### ISSUE THREAD

**Issue by alisalub** [openslide/openslide-python#28]
I'm trying to open a `.scn` file on a CentOS7 machine. `libtiff5` is already installed, and `openslide` itself was installed using `yum`.

When calling `openslide.OpenSlide(filename)` I receive the following error:
```
Traceback (most recent call last):
  File "/home/alisa/PycharmProjects/openslide/read_data.py", line 7, in <module>
    data = openslide.OpenSlide(filename)
  File "/opt/anaconda/anaconda2/envs/oslide/lib/python3.5/site-packages/openslide/__init__.py", line 154, in __init__
    self._osr = lowlevel.open(filename)
  File "/opt/anaconda/anaconda2/envs/oslide/lib/python3.5/site-packages/openslide/lowlevel.py", line 178, in _check_open
    raise OpenSlideError(err)
openslide.lowlevel.OpenSlideError: Couldn't locate TIFF directory for quickhash
```

This is the latest versions of both `openslide` and `openslide-python`.

Thanks.

**Comment by bgilbert** [comment]
[That error](https://github.com/openslide/openslide/blob/199a9c9a9f272dcc984f1f4e9c611143f2bbae10/src/openslide-vendor-leica.c#L794) means that your Leica file is structured in a way that OpenSlide doesn't understand.  Please file a bug over [here](https://github.com/openslide/openslide/issues/new).  Thanks!

**Comment by bgilbert** [comment]
Filed as https://github.com/openslide/openslide/issues/230.  Closing.
