### ISSUE TITLE
deepzoom module is not importable

### ISSUE THREAD

**Issue by DSLituiev** [openslide/openslide-python#30]
## Context

**Issue type** (bug report or feature request): bug
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10):  MacOS 10.12.6
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide Python version** (`openslide.__version__`): '1.1.1'
**OpenSlide version** (`openslide.__library_version__`): 3.4.1 
**Slide format** (e.g. SVS, NDPI, MRXS):  NA

## Details
Running following when installed from `pip` or from github raises Not Found error:
```
import openslide
openslide.deepzoom.DeepZoomGenerator
openslide.deepzoom
```

## Fix:

Add `from openslide import deepzoom` after line 47 to `openslide/__init__.py`

**Comment by bgilbert** [comment]
Generally, in Python, you need to explicitly import each module you want to use.  Sometimes its parent package has already imported it, but you can't depend on that behavior.

In this case, not every user of `openslide` uses `openslide.deepzoom`, and there's no other reason to automatically load it into memory, so we don't.

In your code, you should execute:

```python
import openslide.deepzoom
```
