### ISSUE TITLE
OpenJPEG error

### ISSUE THREAD

**Issue by PingjunChen** [openslide/openslide-python#32]
## Context
Operating system: Ubuntu 16.06
Platform: 64-bit x86,
OpenSlide Python version: newest
OpenSlide version: newest 
Slide format: SVS 

## Details
OpenSlideError: OpenJPEG error: Error decoding tile. Component 1 contains only 32768 blocks while component 0 has 65536 blocks

**Comment by bgilbert** [comment]
What are the actual versions of OpenSlide and OpenSlide Python that you're using?

**Comment by PingjunChen** [comment]
### OpenSlide Python version: 
import openslide
openslide.__version__
u'1.1.1'

### OpenSlide version
$ apt-cache policy openslide-tools 
openslide-tools:
  Installed: 3.4.0-1
  Candidate: 3.4.0-1
  Version table:
 *** 3.4.0-1 0

### Available JPEG related so files. 
/usr/lib/x86_64-linux-gnu/libjpeg.so
/usr/lib/x86_64-linux-gnu/libjpeg.so.8
/usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
/usr/lib/x86_64-linux-gnu/libopenjpeg.so
/usr/lib/x86_64-linux-gnu/libopenjpeg.so.2

**Comment by bgilbert** [comment]
The newest version of OpenSlide is actually 3.4.1.  The problem you're seeing, however, is a [bug in the OpenJPEG library shipped with your version of Ubuntu](https://bugs.launchpad.net/ubuntu/+source/openjpeg/+bug/1404084).  OpenSlide 3.4.1 provides a more detailed error message that explains this.  To address this problem, install OpenJPEG from source.
