### ISSUE TITLE
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by AirFishWang** [openslide/openslide-python#35]
I used to install openslide by "pip install openslide-python", but I got the error when I "import openslide", anyone knows what cause this problem, How can I fix it?

**Comment by supermanhuyu** [comment]
i have the same problem.
you can try 
```
apt install openslide-python
```

**Comment by bgilbert** [comment]
OpenSlide Python requires OpenSlide.  Make sure the OpenSlide library is installed in your library search path.

**Comment by gangli95** [comment]
## Context

**Issue type**
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory
**Operating system**: 
Centos6 (without administrator rights)
**Platform**
x64  
**OpenSlide Python version** 
python3.5  openslide-python 1.1.1


## Details
I tried to install from source and using pip ,but both occured this issue.  I also exported the path when I installed from source(`export LD_LIBRARY_PATH=~/openslide-python-1.1.1:$LD_LIBRARY_PATH` ) , but it didn't work.  If there is any solution for this issues, please tell me. Thanks!
here is the output of error:
`Python 3.5.0 |Continuum Analytics, Inc.| (default, Oct 19 2015, 21:57:25) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openslide
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/DATA/249/gli1/software/openslide-python-1.1.1/openslide/__init__.py", line 29, in <module>
    from openslide import lowlevel
  File "/DATA/249/gli1/software/openslide-python-1.1.1/openslide/lowlevel.py", line 58, in <module>
    _lib = cdll.LoadLibrary('libopenslide.so.0')
  File "/DATA/249/gli1/software/Anaconda3/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/DATA/249/gli1/software/Anaconda3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory
`

**Comment by sbelharbi** [comment]
Hello,
       Any updates on this issue? @gangli95 @bgilbert 
I am facing the same issue: 1. Compiled openslide 3.4.1 locally + added it to the path. 2. Installed openslide-python using pip. 3. `import openslide` raise the error `OSError: /home/.../.local/bin/lib/libopenslide.so.0: cannot open shared object file: No such file or directory`.

Thanks!

**Comment by cassiel007** [comment]
I made the same mistake. 
sudo apt-get install openslide-tools
sudo apt-get install python-openslide
pip install openslide-python
Now I can import python.

**Comment by bgilbert** [comment]
Locking issue to prevent proliferation of support requests.
