### ISSUE TITLE
Performance bottleneck with Openslide and Openseadragon

### ISSUE THREAD

**Issue by zhanghaoyue** [openslide/openslide-python#37]
## Context

**Issue type** (bug report or feature request): performance issue
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10):  Ubuntu 16.04
**Platform** (e.g. 64-bit x86, 32-bit ARM):  64bit x86. i7 7700k, 16gb ddr4 RAM
**OpenSlide Python version** (`openslide.__version__`): 1.1.1
**OpenSlide version** (`openslide.__library_version__`): 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): svs

## Details

Hello,

I built a viewer based on the deepzoom example with openseadragon. I have several mounted folders using cifs, contains a lot of svs format images. I am currently testing it and the performance is terrible. it takes almost several minutes to load the image and when zooming it also takes a while to load. When I set the deepzoom server with local testing images it seems fine. 

I wonder what could be the bottleneck? the way openslide convert svs to dzi on the go? or it's simply bandwidth problem ( although highly unlikely as the file system is across the street and the bandwidth is never a issue with much heavier projects)? 

Any suggestion on improving the loading performance is greatly appreciated!

**Comment by zhanghaoyue** [comment]
@bgilbert  thank you for your reply! I've updated the context part. 
Do you mean the converting processing (generating tiles, etc) is done on my remote file system(including cache)? 
Which cache settings should I take care of? 

Now I can do a workaround to just download the svs to a local temp folder and load it, but it seems not a good practice for a lot of users.

**Comment by bgilbert** [comment]
The processing is done locally, but can involve many small I/O requests to the remote system.  If your CIFS client is not tuned for that (for example, if it expands them to very large requests), or if the server takes a long time to process each request, you will see poor performance.

**Comment by zhanghaoyue** [comment]
Thank you for the reply! I will see what I can do about the remote system.
