### ISSUE TITLE
Read file from web (FTP/HTTP)

### ISSUE THREAD

**Issue by suleymanov** [openslide/openslide-python#38]
## Context

**Issue type** (bug report or feature request): Feature request
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10/Ubuntu/Mac OS
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide Python version** (`openslide.__version__`): 1.1.1
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS): TIF

## Details

Hello!

First of all, thank you for creating and supporting openslide. I started using it couple days ago and find it great!

Thing is, I'm working with and enormous dataset of *.TIF slides that is located at public FTP server. Furthermore, my future research is going to require access slides which are located in Amazon S3 data warehouse. So, the question is: is there any way to access files via FTP/HTTP or is it possible to implement such functionality in the nearest future?

Thank you again.

**Comment by jaharkes** [comment]
I thought this question looked familiar, the same question was asked on the openslide-users mailinglist 2 years ago and I believe the concerns and options given in the response are still valid.

[\[openslide-users\] Re: URL Support](https://lists.andrew.cmu.edu/pipermail/openslide-users/2016-April/001236.html)
