### ISSUE TITLE
Cannot install (v 1.1.0) on Python 3.6 (x64) + Windows 10 x64 

### ISSUE THREAD

**Issue by usamabaig1** [openslide/openslide-python#40]
## Context
LOG:
(py36) C:\Users\Usama Baig>pip install openslide-python==1.1.0
Collecting openslide-python==1.1.0
  Using cached https://files.pythonhosted.org/packages/ae/c3/a691d533287435823f73b6812734ca930cf2ae48a56ebee0197de74e328d/openslide-python-1.1.0.tar.gz
Requirement already satisfied: Pillow in c:\users\usama baig\appdata\local\conda\conda\envs\py36\lib\site-packages (from openslide-python==1.1.0) (5.2.0)
Building wheels for collected packages: openslide-python
  Running setup.py bdist_wheel for openslide-python ... error
  Complete output from command "c:\users\usama baig\appdata\local\conda\conda\envs\py36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\USAMAB~1\\AppData\\Local\\Temp\\pip-install-0lve6p9d\\openslide-python\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\USAMAB~1\AppData\Local\Temp\pip-wheel-mw1pxlfl --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\openslide
  copying openslide\deepzoom.py -> build\lib.win-amd64-3.6\openslide
  copying openslide\lowlevel.py -> build\lib.win-amd64-3.6\openslide
  copying openslide\_version.py -> build\lib.win-amd64-3.6\openslide
  copying openslide\__init__.py -> build\lib.win-amd64-3.6\openslide
  running build_ext
  building 'openslide._convert' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for openslide-python
  Running setup.py clean for openslide-python
Failed to build openslide-python
Installing collected packages: openslide-python
  Running setup.py install for openslide-python ... error
    Complete output from command "c:\users\usama baig\appdata\local\conda\conda\envs\py36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\USAMAB~1\\AppData\\Local\\Temp\\pip-install-0lve6p9d\\openslide-python\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\USAMAB~1\AppData\Local\Temp\pip-record-4u5sv0i_\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\openslide
    copying openslide\deepzoom.py -> build\lib.win-amd64-3.6\openslide
    copying openslide\lowlevel.py -> build\lib.win-amd64-3.6\openslide
    copying openslide\_version.py -> build\lib.win-amd64-3.6\openslide
    copying openslide\__init__.py -> build\lib.win-amd64-3.6\openslide
    running build_ext
    building 'openslide._convert' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command ""c:\users\usama baig\appdata\local\conda\conda\envs\py36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\USAMAB~1\\AppData\\Local\\Temp\\pip-install-0lve6p9d\\openslide-python\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\USAMAB~1\AppData\Local\Temp\pip-record-4u5sv0i_\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\USAMAB~1\AppData\Local\Temp\pip-install-0lve6p9d\openslide-python\

Can you tell me a way to install version 1.1.0? Thanks

**Comment by jxu** [comment]
> error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by slee5777** [comment]
Although installed the "Microsoft Visual C++ Build Tools", I selected the “Windows 10 SDK” (3.6G file).  I still can't install OpenSlide and the similar error message remain.

**Comment by bgilbert** [comment]
Try with OpenSlide Python 1.1.1 instead.  For that version, PyPI has precompiled Python wheels for Python 3.6.

Feel free to reopen if you're still seeing this problem with 1.1.1.
