### ISSUE TITLE
Can't read a tif file using openslide which is  created by vips.

### ISSUE THREAD

**Issue by deepakanandece** [openslide/openslide-python#42]
## Context

**Issue type** (bug report): 
**Operating system** (Ubuntu 16.04): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide Python version** (`'1.1.1'
`): 
**OpenSlide version** (`'3.4.0'`): 
**Slide format** (e.g. .tif): 

## Details
Can't read a tif file using openslide.

**Comment by bgilbert** [comment]
How did you generate the TIFF?  What did you do to read it, and what error did you receive?

**Comment by deepakanandece** [comment]
Now I able to read it. The file was created using vips. Earlier the file was not multi layered, I think that is the reason openslide was not able to read it. Thanks.

**Comment by jlevy44** [comment]
@deepakanandece May I ask how you resolved this issue? I'm also dealing with some single layered images, and have had to use convert to layer them at the expense of some downsampling.
