### ISSUE TITLE
Mosaiced image viewer without creating single large image. Is it possible?

### ISSUE THREAD

**Issue by shivamchaubey** [openslide/openslide-python#43]
Is there any way to stitch multiple images in a grid and deepzoom using deepzoom_server.py. I don't want to stitch images and save it to tiff or any other format, it will take huge RAM and time for 40000 images of resolution 1920X1200. I want to pass these images directly to openseadragon viewer. Any suggestion would be helpful. 

I am using linux and python environemt for the development.

**Comment by bgilbert** [comment]
OpenSlide Python doesn't provide any built-in infrastructure for this, but it should be possible.  You can pass `DeepZoomGenerator` a custom `AbstractSlide` object which proxies read requests to a collection of backend slide objects.
