### ISSUE TITLE
[Question] Handle confocal image stack?

### ISSUE THREAD

**Issue by JieZou1** [openslide/openslide-python#46]
## Context

**Issue type** (bug report or feature request): 
**Operating system** ( Windows 10): 
**Platform** (64-bit): 
**OpenSlide Python version** (1.1.1): 
**OpenSlide version** (3.4.1): 
**Slide format** (NDPI): 

## Details

I have a confocal image stack NDPI file with 11 layers (focal positions).  I have tried opening the NDPI file, but see only resolution pyramid related information. I do not see any confocal related information.

I am just wondering whether OpenSlide could handle this kind of confocal image stack NDPI files. If OpenSlide could not, do you have any suggestions to other Python libraries which can handle it? Many thanks.

**Comment by bgilbert** [comment]
OpenSlide doesn't support multiple focal planes yet; see https://github.com/openslide/openslide/issues/31.
