### ISSUE TITLE
Windows Binaries 2017/11/22 64-bit giving error with openslide-python

### ISSUE THREAD

**Issue by avinash0309** [openslide/openslide-python#49]
Details:
Windows-10 64-bit
Python - 2.7.16

Using:
openslide-python 1.1.1 from pip
Windows Binaries from 2017-11-22

I get entry point not found error:
"The procedure entry point inflateValidate could not be located in the dynamic link library C:\openslide\bin\libintl-8.dll"
and
"The procedure entry point inflateValidate could not be located in the dynamic link library C:\openslide\bin\libxml2-2.dll"

**Comment by avinash0309** [comment]
I find out that others have resolved by adding below line 
os.environ['PATH'] = "path-to-openslide-bin" + ";" + os.environ['PATH'] 
to lowlevel.py.

Even after adding this line I'm getting the same error.
Please help me with this and also help me where I need to add above line in lowlevel.py file.

Thanking you.

**Comment by jaharkes** [comment]
From some quick googling it looks like you are either missing the zlib dll, or your system is finding another possibly older one in your dll/program search path that happens to be missing the `validateInflate` function.

Modifying the PATH environment is an attempt to force a different order in the search path which would only help avoid the dynamic linker from picking up the older version if you have the correct one installed in the openslide binary directory. You shouldn't have to edit the lowlevel.py file, just changing the PATH environment variable would fix it too, although I'm not sure how that is done on Windows.

I assume you replaced "path-to-openslide-bin" with the actual path where you installed the openslide library, in which case the most likely cause is a missing zlib dll.

**Comment by avinash0309** [comment]
Thanks for your help, but no luck. I'm facing the same issue and I have zlib1.dll in the openslide lib path.

Here is the step which I followed:
1. pip install openslide python
2. downloaded the openslide binaries and set this path to the environmental path variable.
3. checked with changing environmental path variable with a different order.
 4. by googling I found out- need to add: os.environ['PATH'] = "path-to-openslide-bin" + ";" + os.environ['PATH'] to lowlevel.py. But where exactly this line I need to add is my question?

even doing all these I'm getting the following error:
"The procedure entry point inflateValidate could not be located in the dynamic link library C:\openslide\bin\libintl-8.dll"
and
"The procedure entry point inflateValidate could not be located in the dynamic link library C:\openslide\bin\libxml2-2.dll"

Please help me out where I'm going wrong and how to fix this.

Thanks for your help in advance.

**Comment by bgilbert** [comment]
`PATH` should be changed in your system environment variables, not directly in the OpenSlide Python code.  But @jaharkes is right, the problem is likely an older zlib DLL elsewhere in your search path.
