### ISSUE TITLE
converting svs to jpeg 

### ISSUE THREAD

**Issue by dkoen** [openslide/openslide-python#50]
## Context

**Issue type** (bug report or feature request): feature request 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 7 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide Python version** (`openslide.__version__`): 
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS): svs 

## Details

I would like to convert the large SVS files I have into smaller jpeg files. 

I found the following guide on the problem: https://developer.ibm.com/articles/an-automatic-method-to-identify-tissues-from-big-whole-slide-images-pt1/ 

but the functions called in the guide appear to be deprecated. 

I have figured out how to save an individual tile as a jpeg image but now how to save the whole slide image as a smaller jpeg. 

Please advise!

**Comment by jxu** [comment]
Does thumbnail function https://openslide.org/api/python/#openslide.OpenSlide.get_thumbnail and Pillow's image save not work?

**Comment by bgilbert** [comment]
Closing per https://github.com/openslide/openslide-python/issues/50#issuecomment-508596908.  Please reopen if this isn't working for you.
