### ISSUE TITLE
openslide.lowlevel.OpenSlideError: OpenJPEG error: tcd_decode: incomplete bistream

### ISSUE THREAD

**Issue by yasohasakii** [openslide/openslide-python#53]
## Context

**Issue type** (bug report): 
**Operating system** (CentOS): 
**Platform** (Linux 64bit): 
**OpenSlide Python version** (`2.7`): 
**OpenSlide version** (`1.1.1`): 
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details
Hi, when i run `image=np.array(slide.read_region((20000,20000),0,(4000,4000)))`, i got error like title. and other region like `slide.read_region((0,0),0,(4000,4000))` has no problem. So how can I fix this error.

**Comment by zseferbekova** [comment]
Having the same issue

**Comment by xhm1014** [comment]
@yasohasakii  have you solved your above mentioned problems? I also encounter this problem, but have not found good solutions. Thanks

**Comment by yasohasakii** [comment]
It's not an error raised by openslide but maybe is caused by data overflow, you can use `slide.read_region` with a smaller region size or try with pyvips.
