### ISSUE TITLE
convert jpeg to svs or mrxs

### ISSUE THREAD

**Issue by yasohasakii** [openslide/openslide-python#56]
## Context

**Issue type** (bug report or feature request): feature request
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): CentOS 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide Python version** (`openslide.__version__`): 1.1.1
**OpenSlide version** (`openslide.__library_version__`): don't know
**Slide format** (e.g. SVS, NDPI, MRXS): MRXS

## Details
Hi! Is there any python API for converting jpeg or png files to MRXS or SVS files? Saving as jpeg files occupied me too much memory, thanks!

**Comment by bgilbert** [comment]
Nope.  By design, OpenSlide can only read whole-slide image files, not write them.
