### ISSUE TITLE
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by michaelmooreny** [openslide/openslide-python#59]
## Context

I am trying to install openslide for a project I'm working on

**Issue type** (bug report or feature request): 

After running:

sudo apt-get install openslide-tools
sudo apt-get install python-openslide
sudo pip3 --proxy http://bcp3.cumc.columbia.edu:8080 install openslide-python

I recieve the follwoing error when importing openslide:

Traceback (most recent call last):
  File "script_for_mm.py", line 3, in <module>
    import openslide
  File "/usr/local/lib/python3.5/dist-packages/openslide/__init__.py", line 29, in <module>
    from openslide import lowlevel
  File "/usr/local/lib/python3.5/dist-packages/openslide/lowlevel.py", line 58, in <module>
    _lib = cdll.LoadLibrary('libopenslide.so.0')
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 

Ubuntu 16.04

**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide Python version** (`openslide.__version__`): 

1.1.1

**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS): 

.scn

**Comment by markemus** [comment]
Our install has this problem too and we're not sure why. We've been able to work around it by running:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH":/usr/lib/x86_64-linux-gnu:"`

in bash before calling python. If anyone knows of a permanent solution that would be a big help but this works as a temporary fix.

**Comment by superxudou** [comment]
I have the same problem. 
i found 
![image](https://user-images.githubusercontent.com/40804296/70387487-75538d00-19e0-11ea-9f79-cdc2c7e5eaf2.png)
but it did not work ...
 My system is CentOS

**Comment by Abhinav-Telukunta** [comment]
Hi @michaelmooreny. You need to install openslide-python in the following way:

1. sudo apt update && apt install -y openslide-tools
2.  pip install openslide-python

Then try to run the command :
## import openslide

Then it will work

**Comment by j-sieger** [comment]
@Abhinav-Telukunta : How to solve this issue on Amazon Linux server(EC2). As it won't support `apt`

**Comment by alanocallaghan** [comment]
I think Amazon Linux Server EC2 uses OpenSUSE, in which case you'd want to try `zypper install openslide-tools`

**Comment by bgilbert** [comment]
The current release of OpenSlide no longer supports Ubuntu 16.04, but if OpenSlide was installed from `apt`, it's not clear why OpenSlide Python would have failed to find it.

On any reasonably current Linux, macOS, or Windows system, you can now install OpenSlide [directly from PyPI](https://pypi.org/project/openslide-bin/) and OpenSlide Python 1.4.0+ will find it.  So, the easiest way to get a working OpenSlide Python installation is now:

```bash
pip install openslide-python openslide-bin
```
