### ISSUE TITLE
Feature was deprecated in 3.7 back in 2013

### ISSUE THREAD

**Issue by fireofearth** [openslide/openslide-python#60]
FYI: Feature was deprecated in 3.7 back in 2013 and causes gcc compilation error which attempting to `pip install` this library (I'm using pip in Anaconda). A work around is to git clone, delete the line `Feature` and `features={...}` and then call `pip setup.py install` to install this package from source.

## Details

```python
import os
from setuptools import setup, Extension, Feature # delete Feature

# Load version string
_verfile = os.path.join(os.path.dirname(__file__), 'openslide', '_version.py')
with open(_verfile) as _fh:
    exec(_fh.read())

with open('README.rst') as _fh:
    _long_description = _fh.read()

setup(
    name='openslide-python',
    version=__version__,
    packages=[
        'openslide',
    ],
    features={ # delete features={...}
        'performance': Feature(
            'performance-enhancing extension module',
            standard=True,
            ext_modules=[
                Extension('openslide._convert', ['openslide/_convert.c']),
            ],
        ),
    },
```

Question: is there a way to use the performance-enhancing extension module as feature another way? Is this module useful?

**Comment by keeganwitt** [comment]
I guess since there's been more activity on #80, we should close this issue as a dupe (even though it was opened first).

**Comment by fireofearth** [comment]
Sounds good.
