### ISSUE TITLE
Build a realy simple POST request using jQuery with multiserver

### ISSUE THREAD

**Issue by luistelmocosta** [openslide/openslide-python#61]
## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64
**OpenSlide Python version** (`openslide.__version__`): 
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details

I am using openslide with deepzoom and I would like to send a POST request into my server. However, I'm not getting the format of the request.

Is there any example on how to do this?

I'm using Jquery to make the request and I want something really simple. Like this:

```
function send_annotation(ann) {

            $.ajax({
                type: "POST",
                url: "/save_annotations",
                data: JSON.stringify(ann),
                contentType: "application/json; charset=utf-8",
                success: function (msg) {
                    console.log('Annotations saved');
                }
            });

        }
```

In the `deep_zoom_multiserver` I just want to print the array that I am sending:

```
@app.route('/save_annotations', methods=['POST'])
def save_annotations(ann):
    print('ann')

Kind regards
```

**Comment by jaharkes** [comment]
The json doesn't get passed as an argument in Flask. You can try the following and should see a dict containing an 'ann' key with your data.

    print( request.get_json() )

**Comment by luistelmocosta** [comment]
My main problem is with routing. I would be glad if that request returns something just to check if the routing is correct. 

But in my console, I get: ` '_xsrf' argument missing from POST`

**Comment by jaharkes** [comment]
Odd, that must to be some sort of cross-site-request-forgery token, but I thought Flask didn't insert those by default and left it up to a form validation framework which I don't think our example server is using.

https://flask.palletsprojects.com/en/1.1.x/security/#cross-site-request-forgery-csrf

**Comment by bgilbert** [comment]
This doesn't look like it's an issue with OpenSlide Python, so I'll close.  Please feel free to reopen if you have additional information pointing to an OpenSlide Python issue.
