### ISSUE TITLE
The read_region function behavior is odd.

### ISSUE THREAD

**Issue by teramototoya** [openslide/openslide-python#62]
## Context

**Issue type** (bug report or feature request):  bug
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10):  Ubuntu 18.04
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit x86
**OpenSlide Python version** (`openslide.__version__`): 1.1.1
**OpenSlide version** (`openslide.__library_version__`): 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS):  svs

## Details
I am using the python API of openslide packages to read some svs file. When I use the read_region function, sometimes it return a odd image.

I set the level 0 location and the specific level (other than 0) to the read_region function.
(ex. read_region(location=(at level 0 index), level=2, size=size)
When shifting the index by 1 pixel, I gives a odd image. (ex. Figure)

There is regularity in change, which matches the value of downsampling.
What is the cause?
I've reinstalled openslide, python but the problem persists. There are no problems when I use other pc (linux or windows) 

Thank you.

sample code
```python
with OpenSlide(wpath) as wsi:
    w,h = wsi.level_dimensions[0]
    x = np.random.randint(h)
    y = np.random.randint(w)
    diff = 7
    plt.figure(figsize=(diff,diff))
    for i in range(diff):
        for j in range(diff):
            plt.subplot(diff, diff, i*diff+j+1)
            im = wsi.read_region(location=(x+(i-diff//2),y-(j-diff//2)), level=2, size=(size,size))
            plt.imshow(im)
    plt.show()
```

![fig](https://user-images.githubusercontent.com/13429694/65766515-38f4ec80-e166-11e9-9f55-72669f1e535a.png)

**Comment by teramototoya** [comment]
I tried this solution but it didn't work. 
https://github.com/openslide/openslide/issues/278

**Comment by teramototoya** [comment]
In windows10, openslide works fine.

![good](https://user-images.githubusercontent.com/13429694/65858669-827d4b80-e3a1-11e9-930d-c525daffd91d.png)

**Comment by teramototoya** [comment]
Solved this way!!!
```
conda install pixman=0.36.0
```
https://github.com/computationalpathologygroup/ASAP/issues/161

Closed this issue!

**Comment by ntomita** [comment]
@teramototoya  OMG I had exactly the same issue and your solution works perfectly! Thanks!!

**Comment by schaffman5** [comment]
Thanks.  On a Mac, I saw the same problems with the latest homebrew version of pixman (0.38.4).  The older version of pixman (0.36.0) fixes this issue for me too.  To install:

`brew install https://homebrew.bintray.com/bottles/pixman-0.36.0.mojave.bottle.tar.gz`

**Comment by saichandra1** [comment]
Even after installing pixman i had issue but saving image in TIFF format instead of pnf solved my problem
