### ISSUE TITLE
error in importing openlide

### ISSUE THREAD

**Issue by saisriteja** [openslide/openslide-python#63]
I have tried to install in opensLide in collab so I got the below error.....can anyone help me with this....

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-9-bb94c1b557c7> in <module>()
----> 1 import openslide

3 frames
/usr/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

**Comment by jaharkes** [comment]
Not sure what collab is but it looks to me like the actual openslide library is not installed,only the python wrappe.

Most of the openslide functionality is implemented in a C library which does not get installed as part of 'pip install openslide'.

**Comment by NourEddy** [comment]
I also have a problem when I import openSlide 
import openslide
Traceback (most recent call last):

  File "<ipython-input-1-bb94c1b557c7>", line 1, in <module>
    import openslide

  File "C:\Users\China\Anaconda3\envs\machine\lib\site-packages\openslide\__init__.py", line 29, in <module>
    from openslide import lowlevel

  File "C:\Users\China\Anaconda3\envs\machine\lib\site-packages\openslide\lowlevel.py", line 41, in <module>
    _lib = cdll.LoadLibrary('libopenslide-0.dll')

  File "C:\Users\China\Anaconda3\envs\machine\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)

  File "C:\Users\China\Anaconda3\envs\machine\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 193] %1 n’est pas une application Win32 valide

**Comment by markemus** [comment]
See workaround here: https://github.com/openslide/openslide-python/issues/59#issuecomment-551213739

**Comment by bgilbert** [comment]
Closing to limit the proliferation of tickets about SO/DLL search path issues.

**Comment by markemus** [comment]
@bgilbert it seems a number of us are having this issue- is there an open ticket for this already, or is it a problem with the underlying openslide library/install, or are you just not sure what's causing it? It's a consistent problem for our team even with the workaround and it would be really helpful if we could figure out what's causing it.

**Comment by ejri** [comment]
@saisriteja @markemus I'm wondering if you have been able to run openslide in colab. The work around mentioned does not work. Installing openslide directly through pip install, and through conda doesn't seem to work either. 

Any ideas?

**Comment by markemus** [comment]
@ejri do you have the openslide-tools library installed? I don't think pip install installs that.

**Comment by ejri** [comment]
@markemus  yeah I install openslide tools seprately, openslide-tools gets installed without issues. 

pip installing openslide

gives out this error:

```
  Downloading https://files.pythonhosted.org/packages/26/5a/5b0adeabce81f018a9e4ffe9a419536064bc95c1b12194aff9b7e48f91f7/openslide-python-1.1.1.tar.gz (312kB)
     |████████████████████████████████| 317kB 2.7MB/s 
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full comman
```

and opening any of the files within the cloned git hub repo (from git cloning the openslide-python repo),
gives out the no module error.
```
File "deepzoom_multiserver.py", line 24, in <module>
    import openslide
ModuleNotFoundError: No module named 'openslide'
```
