### ISSUE TITLE
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

### ISSUE THREAD

**Issue by yangyunshuai** [openslide/openslide-python#64]
## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide Python version** (`openslide.__version__`): 
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS):

**Comment by SCP-173-cool** [comment]
The file details？

**Comment by yangyunshuai** [comment]
the file is ok for my mac， but don't work for linux

**Comment by yangyunshuai** [comment]
my linux's environment is Pillow6.2.1  openslide-python1.1.1  opensilde3.4.0

**Comment by bgilbert** [comment]
There's not enough information here to act on this report.  Closing; feel free to reopen with details about the file and why you expect it to work.
