### ISSUE TITLE
MRXS file  seem error with read_region function

### ISSUE THREAD

**Issue by AndrewTal** [openslide/openslide-python#65]
## MRXS file seem error with read_region function
 
**Operating system** (Ubuntu 18.04): 
**Slide format** (MRXS): 

## Details
Code:
path= './CMU-1-Saved-1_16.mrxs'
slide = OpenSlide(path)
slide.read_region((0,0),level,slide.level_dimensions[level])

only level==0 can correct display image, otherwise image with read_region will like this:
 

(slide.read_region((0,0),3,slide.level_dimensions[3]))

and the MRXS flie come from (https://openslide.org/formats/mirax/)

Is any wrong with my code?

**Comment by AndrewTal** [comment]
like this :
![1576551684(1)](https://user-images.githubusercontent.com/49064155/70961800-e1f41900-20bd-11ea-8fca-ec7156fc4cb8.png)

**Comment by Nurfen** [comment]
Your code works for me. 
It looks like there is something wrong with the alpha channel.
Maybe it is something with how the image is saved. Do you have the same result when using the below code?

```
im = slide.read_region((0,0),level,slide.level_dimensions[level])
im.show()
```

**Comment by AndrewTal** [comment]
> Your code works for me.
> It looks like there is something wrong with the alpha channel.
> Maybe it is something with how the image is saved. Do you have the same result when using the below code?
> 
> ```
> im = slide.read_region((0,0),level,slide.level_dimensions[level])
> im.show()
>

**Comment by AndrewTal** [comment]
> Your code works for me.
> It looks like there is something wrong with the alpha channel.
> Maybe it is something with how the image is saved. Do you have the same result when using the below code?
> 
> ```
> im = slide.read_region((0,0),level,slide.level_dimensions[level])
> im.show()
> ```

**Comment by AndrewTal** [comment]
![adc2a37f900cfb3ea04b610d928bd0d](https://user-images.githubusercontent.com/49064155/71671042-d8043280-2dac-11ea-899a-48366ee3e543.png)
![cffdf9844bde627e37044d10f7b2f6e](https://user-images.githubusercontent.com/49064155/71671043-da668c80-2dac-11ea-9e32-bae4f2bd840b.png)
![f7105f7c2b3a16588e5a1b0cb773d7c](https://user-images.githubusercontent.com/49064155/71671047-dcc8e680-2dac-11ea-82f1-1e0bd568dc7c.png)

i think it get the same problem emmmm

**Comment by AndrewTal** [comment]
![cffdf9844bde627e37044d10f7b2f6e](https://user-images.githubusercontent.com/49064155/71671156-33362500-2dad-11ea-83be-54256b0dceb6.png)
![f7105f7c2b3a16588e5a1b0cb773d7c](https://user-images.githubusercontent.com/49064155/71671169-3e895080-2dad-11ea-8613-8a946bc560df.png)
![adc2a37f900cfb3ea04b610d928bd0d](https://user-images.githubusercontent.com/49064155/71671174-447f3180-2dad-11ea-94fd-3610bad9113e.png)

i think it get the same problem emmmm

**Comment by Nurfen** [comment]
And what if you try `img = img.convert('RGB')` first?
If this doesn't solve it, you will have to wait for the pro's to arrive  ... :/

**Comment by AndrewTal** [comment]
![f73867c9422d60b5fdfb25dc61e4366](https://user-images.githubusercontent.com/49064155/71673557-10f3d580-2db4-11ea-921f-0c02285f0e9e.png)

emmm  not ok , thank you very much    : )

**Comment by ThomasChevalier** [comment]
I have the same problem as yours. When testing it with a low level (1, 2 or 3), I found that there are always two numbers i and j such that if x%D==i and y%D==j there is a better result (where x and y are the coordinates of the top left corner of the region and D is the downsample). For example with level 1 if x%2 == 0 and y%2 == 1 there is no problem (provided that the width or the height is not too high). For level 2 its (2; 1) and for level 3 (2; 5). I have not the same image as yours so those numbers could be different.
I don't know if this remark is relevant, but it might show that it is an alignment problem (as underlined in the comment linked by nslay in https://github.com/openslide/openslide/issues/256).

**Comment by ThomasChevalier** [comment]
This issue is solved in https://github.com/openslide/openslide/issues/278

**Comment by bgilbert** [comment]
Closing per https://github.com/openslide/openslide-python/issues/65#issuecomment-573330189 and https://github.com/openslide/openslide/issues/278#issuecomment-524377558.  Please reopen if you're still seeing this issue.
