### ISSUE TITLE
 libopenslide.so.0 Error and install python-openslide Error

### ISSUE THREAD

**Issue by PengzhongSun** [openslide/openslide-python#67]
## Context

**Issue type** (bug report or feature request):  Can't import openslide right
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10):  Ubuntu 18.04
**Platform** (e.g. 64-bit x86, 32-bit ARM):  64-bit x86
**OpenSlide Python version** (`openslide.__version__`): 1.1.1
**OpenSlide version** (`openslide.__library_version__`):  None
**Slide format** (e.g. SVS, NDPI, MRXS):  svs

## Details
When I 'import openslide', I first encounter this problem, 
![图片](https://user-images.githubusercontent.com/43957007/72140303-7145d100-33cb-11ea-8de4-b49173707ec9.png)

And I find someone said this problem can be solved by 'sudo apt install python-openslide'.
Then I encounter another problem, I can't locate this package.
![图片](https://user-images.githubusercontent.com/43957007/72140542-f16c3680-33cb-11ea-9f2c-787ae8e72d6d.png)

So How can I solve these problems and import openslide right?
Thank you！

**Comment by bgilbert** [comment]
OpenSlide Python requires OpenSlide.  You should be able to install OpenSlide on Ubuntu with `sudo apt-get install openslide-tools`.  I can't read the error message, so I don't know why this is failing for you.
