### ISSUE TITLE
Cannot open path with non ascii character

### ISSUE THREAD

**Issue by ThomasChevalier** [openslide/openslide-python#68]
## Context

**Issue type**: bug
**Operating system**: Windows 10
**Platform**: 64-bit
**OpenSlide Python version**:  1.1.1
**OpenSlide version**: 3.4.1
**Slide format**: MRXS (possibly other format)

## Details
On Windows, trying to open a filename with non ascii character in its path results in an `OpenSlideError`.
This bug doesn't exist in Linux.

## Steps to reproduce
```python
import openslide as op

filename = "D:\\non_ascii_path_é\\CMU-1.mrxs"
slide = op.OpenSlide(filename)
print("Level dimensions: ", slide.level_dimensions)
```

Expected result : `Level dimensions:  ((109240, 220696), (54620, 110348), (27310, 55174), (13655, 27587), (6827, 13793), (3413, 6896), (1706, 3448), (853, 1724), (426, 862), (213, 431)) `
Get :
```
Traceback (most recent call last):
  File ".\test_ascii_path.py", line 4, in <module>
    slide = op.OpenSlide(filename)
  File "D:\Programmes\Python38\lib\site-packages\openslide\__init__.py", line 154, in __init__
    self._osr = lowlevel.open(filename)
  File "D:\Programmes\Python38\lib\site-packages\openslide\lowlevel.py", line 178, in _check_open
    raise OpenSlideError(err)
openslide.lowlevel.OpenSlideError: Couldn't open D:\non_ascii_path_é\CMU-1\Slidedat.ini: No such file or directory
```

## Notes
I have observed similar behaviour with other formats but error codes are different.
For Trestle and Generic tiff : `openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file`
I don't think it is related with the format, it's more like the C openstack backend didn't process the received filename in the right encoding.

**Comment by bgilbert** [comment]
Can you try with OpenSlide built from Git master?  openslide/openslide@89bba00be872c27fdd1f7ef08a59e15546165c72 should have fixed this on the OpenSlide side.

**Comment by bgilbert** [comment]
This should be fixed in current Git.  Closing.
