### ISSUE TITLE
OpenSlide._filename vs ImageSlide._file_arg inconsistency

### ISSUE THREAD

**Issue by DragonDuck** [openslide/openslide-python#74]
## Context

**Issue type** (bug report or feature request): Bug report, possibly a feature request
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Ubuntu
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit x86
**OpenSlide Python version** (`openslide.__version__`): 1.1.1
**OpenSlide version** (`openslide.__library_version__`): 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): N/A

## Details

When opening an image with openslide.open_slide, `OpenSlide` objects have the `_filename` attribute whereas `ImageSlide` objects have a `_file_arg` attribute. I'm unsure whether this is intentional, but would it be cleaner, since the classes are supposed to be wrappers, to rename the file path attribute to the same name for both classes?

**Comment by bgilbert** [comment]
Conventionally in Python, the leading underscore indicates that these are private fields and should not be accessed from outside the class.  So, the inconsistency wouldn't normally make a difference.  How are you using the classes that requires access to these fields?

**Comment by bgilbert** [comment]
Closing due to lack of response.  Please feel free to reopen if you can provide the requested info.
