### ISSUE TITLE
Cannot import open-slide in jupyter notebook.

### ISSUE THREAD

**Issue by pranathichunduru** [openslide/openslide-python#77]
## Context
I am unable to import open-slide python in my jupyter notebook(virtual environment)

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Red Hat Enterprise Linux Workstation.Version- 7.7 (Maipo)
**Platform** (e.g. 64-bit x86, 32-bit ARM):  Linux 3.10.0-1062.12.1.el7.x86_64
**OpenSlide version**: 
**Slide format** (e.g. SVS, NDPI, MRXS): .svs

## Details
```
OSError                                   Traceback (most recent call last)
<ipython-input-2-1d3bc907299c> in <module>
     16 print(os.environ["PATH"])
     17 
---> 18 import openslide
     19 # from openslide import OpenSlide, OpenSlideUnsupportedFormatError
     20 

/working/lupolab/pranathi/conda/envs/python3titan/lib/python3.6/site-packages/openslide/__init__.py in <module>
     27 from PIL import Image
     28 
---> 29 from openslide import lowlevel
     30 
     31 # For the benefit of library users

/working/lupolab/pranathi/conda/envs/python3titan/lib/python3.6/site-packages/openslide/lowlevel.py in <module>
     58         _lib = cdll.LoadLibrary(_lib)
     59 else:
---> 60     _lib = cdll.LoadLibrary('libopenslide.so.0')
     61 
     62 try:

/working/lupolab/pranathi/conda/envs/pchunduru/lib/python3.6/ctypes/__init__.py in LoadLibrary(self, name)
    424 
    425     def LoadLibrary(self, name):
--> 426         return self._dlltype(name)
    427 
    428 cdll = LibraryLoader(CDLL)

/working/lupolab/pranathi/conda/envs/pchunduru/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

```

I installed  open-slide using anaconda in my virtual environment:
`conda install -c bioconda openslide`

Installed openslide python using:
`conda install -c bioconda openslide-python`

After looking up on stackoverflow and github forums. I tried adding
`# os.environ["PATH"] =  "path/openslide/bin"  + ":" + os.environ["PATH"]`. in lowlevel.py file
However I cannot find bin folder in openslide. 
libopenslide.so.0 This file exists in python libraries (in virtual environment) but not in openslide.

I am trying to use openslide for digital pathology image analysis that are in .svs format.
I am scripting my code in python.
Also I donot have root access to use "yum install openslide" von linux platform ,since I am working on shared server and I am not the admin.

Please let me know if you need any further info to understand the issue better.
Appreciate any help !

**Comment by ejri** [comment]
There seems to be an issue with it. 


pip install in colab/jupyter and terminal gives out this error:

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ZackPashkin** [comment]
have the same issue

> There seems to be an issue with it.
> 
> pip install in colab/jupyter and terminal gives out this error:
> 
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ZackPashkin** [comment]
Solved the issue
Workaround:

pip uninstall setuptools
pip install setuptools=v45.3.0
sudo apt-get install openslide-tools
sudo apt-get install python-openslide
pip install openslide-python


import openslide

How it will help who has the same problem installing openslide

**Comment by ejri** [comment]
Cool! Thanks, @ZackPashkin. Your work around seems to work for me!! 
 
Just a comment about syntax, to pip install the specific version of a library, the operator should be "==" not a single one.
 
`pip install setuptools=v45.3.0`

it should be:
 `pip install setuptools==45.3.0`

**Comment by bgilbert** [comment]
@pranathichunduru Setting `PATH` for libraries only works on Windows.  On Linux, if `libopenslide.so.0` is installed to a non-standard directory, you need to put that directory's path in `LD_LIBRARY_PATH` instead.

This doesn't seem to be an OpenSlide Python bug, so I'll close.

**Comment by az-ad** [comment]
after running 
import openslide in jupyter notebook I also found error:

`Traceback (most recent call last):

  File ~\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:3526 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[19], line 1
    import openslide

  File ~\anaconda3\Lib\site-packages\openslide\__init__.py:31
    from openslide import lowlevel

  File ~\anaconda3\Lib\site-packages\openslide\lowlevel.py:54
    os.environ['PATH'] = "C:\Users\HP\anaconda3\Lib\site-packages\openslide\openslide-win64-20231011\bin"+";" + os.environ['PATH']
                                                                                                         ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape` 

how can I solve this

**Comment by bgilbert** [comment]
In current versions of Python, you should use `os.add_dll_directory()` to specify the path to OpenSlide binaries on Windows.  See the [OpenSlide Python installation instructions](https://openslide.org/api/python/#installing) for more information.  Do not specify the path by manually modifying the installed copy of OpenSlide Python.

**Comment by az-ad** [comment]
Thank you so much. It works.
