### ISSUE TITLE
Remove Feature from setup.py

### ISSUE THREAD

**Issue by sikuan** [openslide/openslide-python#80]
Hi,

from setuptools 46.0, `Feature` support was completely removed: https://github.com/pypa/setuptools/commit/c71969013d726c5cbd06dc81770ab064f3e783ff and https://github.com/pypa/setuptools/pull/1979.

There are some `Feature` usages in this module:

https://github.com/openslide/openslide-python/blob/8e2c948fa66dcda34e2627b9afcde50ebfa301af/setup.py#L2

https://github.com/openslide/openslide-python/blob/8e2c948fa66dcda34e2627b9afcde50ebfa301af/setup.py#L19

So suppose these should be removed. Thanks.

**Comment by alessiamarcolini** [comment]
Dear everyone, as a gesture of courtesy towards the community, we forked the openslide-python repo and we released it on PyPI. Please note that this is a **temporary workaround** to have openslide-python installable via pip without the setuptools issue.

https://pypi.org/project/openslide-wrapper/1.1.2/

cc @ernestoarbitrio and @nicolebussola

**Comment by PiRK** [comment]
I made a patch in a repository I cloned manually, before realizing that there was already an openslide-python repo on github.
https://github.com/PiRK/openslide/commit/c11b26af4e50765a2c9a31a314087f1b42ca7d96

It works for me, but I don't really understand what Feature was used for. I hope my change didn't break anything else.

Should I try to submit a pull request with my patch?

**Comment by keeganwitt** [comment]
Related MR: #76.

**Comment by c-arthurs** [comment]
I think this is what was causing me to get the _ImportError: cannot import name 'Feature' from 'setuptools'_ error when installing openslide-python.
Obviously not a permanent fix but downgrading the setuptools to 45 will let you install openslide-python:
**pip install setuptools==45**

**Comment by ericmjl** [comment]
Hello friends! I have a colleague who ran into the same set of issues here. I do see that the source code on the latest `master` branch is up-to-date, and doesn't use `Feature` in `setup.py`. Would there be a possibility of cutting a patch release on PyPI, to make installation easier for all users please? tagging @hugovk and @bgilbert, who are (I think) the biggest code contributors here. Given that the package is up on PyPI, I hope it won't be too big of a burden for you two!

**Comment by hugovk** [comment]
Hello! I'm just an occasional contributor and don't have merge or release rights for this repo. 

@bgilbert is listed as maintainer on https://pypi.org/project/openslide-python/ and hopefully can make a release soon!

**Comment by log0ymxm** [comment]
This is pretty old for a really minor issue that totally blocks most new installs. @bgilbert can we get a release to fix this, or add more maintainers to this repo?

**Comment by bgilbert** [comment]
Yup, we'll get a new release out soon.

**Comment by bgilbert** [comment]
[OpenSlide Python 1.1.2](https://pypi.org/project/openslide-python/1.1.2/) has been released with a fix for this issue.  Thanks for your patience and persistence, all.
