### ISSUE TITLE
 Get numpy RGB of whole slide image using OpenSlide/large_image from NDPI pyramidal file

### ISSUE THREAD

**Issue by asmagen** [openslide/openslide-python#82]
I’m using OpenSlide/large_image to open NDPI pyramidal files and I would like to get an RGB numpy array for a specific magnification of interest, but I can’t find anywhere in the documentation how to do that. What’s the easiest way to get the RGB 3d array?

**Comment by kimalaacer** [comment]
Did you find a solution? 
I am interested of getting the np array of level[0].
