### ISSUE TITLE
DeprecationWarning import Python3.9

### ISSUE THREAD

**Issue by ernestoarbitrio** [openslide/openslide-python#83]
## Context
**OpenSlide Python version** (`openslide.__version__`): 1.1.1

## Details
Considering that in here https://github.com/openslide/openslide-python/commit/8b0ec81857177cd99239895fcfec0f2e0231328e is addressed the import warning `abc` for `python 3.9`, I was wondering when a new version will be released that avoid that `DeprecationWarning`

**Comment by bgilbert** [comment]
[OpenSlide Python 1.1.2](https://pypi.org/project/openslide-python/1.1.2/) has been released with a fix for this issue.
