### ISSUE TITLE
openslide for python 3.6.9

### ISSUE THREAD

**Issue by Adamszk** [openslide/openslide-python#86]
## Context
Import Issue:
Linux opensuse leap 15.0
64-bit x86
OpenSlide Latest version

I have installed openslide-tools and openslide-python.  When I use python 2.7.14 version, the import is working.  However when I use python 3.6.9 version, the python gives me an error message,

>>> import openslide
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'openslide'

I did pip2 list and openslide-python 1.1.1 is listed in python3.

**Comment by bgilbert** [comment]
It sounds as though OpenSlide Python isn't installed in the package path of your Python 3 interpreter.  Check the output of `pip3 list`.
