### ISSUE TITLE
Classic PIL doesn't understand io.UnsupportedOperation.

### ISSUE THREAD

**Issue by ozdenurucar** [openslide/openslide-python#89]
## Context

**Issue type** (bug report or feature request): 
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
**OpenSlide Python version** (`openslide.__version__`): 
**OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (e.g. SVS, NDPI, MRXS): 

## Details

I try deepzoom example with "CMU-1-Small-Region.svs"  sample.  Page opened and throw "Not Supported" 
exception at 
```
class PILBytesIO(BytesIO):
    def fileno(self):
        '''Classic PIL doesn't understand io.UnsupportedOperation.'''
        raise AttributeError('Not supported')
```
How can i resolve this problem?

**Comment by bgilbert** [comment]
What operating system are you using, and what version of PIL or Pillow?

**Comment by ozdenurucar** [comment]
I am using win10 operating system and Pillow version is 7.2.0.

**Comment by bgilbert** [comment]
I'm not seeing this on Linux with Pillow 7.2.0, but it could be Windows-specific.

**Comment by bgilbert** [comment]
The code you quoted is no longer present in Git HEAD.  Could you try again with current Git and report if you're still seeing the issue?

**Comment by bgilbert** [comment]
This code is no longer present in Git HEAD, so I'll close this as fixed.  Thanks for the report.
