### ISSUE TITLE
Update OpenSeadragon

### ISSUE THREAD

**Issue by bgilbert** [openslide/openslide-python#92]
Update the bundled OpenSeadragon to a current version.  Update the code for any API deprecations.  Verify that there are no rendering glitches.

**Comment by linboqiao** [comment]
Hi, I use the command 
"python  deepzoom_multiserver.py /path/to/TCGA-slides" 
to start a webserver, but it is not properly presented. 
As you can see in the screen capture, the left part and the top part are missing.

Could you fix this bug?

![2021-07-23 17-46-02 的屏幕截图](https://user-images.githubusercontent.com/7816466/126765399-0f6b6ada-07d0-4f0c-9317-72a20a5e623b.png)
