### ISSUE TITLE
FileNotFoundError: Could not find module 'libopenslide-0.dll'.

### ISSUE THREAD

**Issue by ernestoarbitrio** [openslide/openslide-python#98]
## Context

**Issue type** (bug report or feature request): bug
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 10
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64 bit
**OpenSlide Python version** (`openslide.__version__`): 1.1.2
**OpenSlide version** (`openslide.__library_version__`): openslide-win64-20171122

## Details
The problem happens only with `python 3.8` while running a test suite that import openslide. Openslide bin directory is in the PATH env variable but:
```
    import openslide
c:\python38\lib\site-packages\openslide\__init__.py:35: in <module>
    from openslide import lowlevel
c:\python38\lib\site-packages\openslide\lowlevel.py:43: in <module>
    _lib = cdll.LoadLibrary('libopenslide-0.dll')
c:\python38\lib\ctypes\__init__.py:447: in LoadLibrary
    return self._dlltype(name)
c:\python38\lib\ctypes\__init__.py:369: in __init__
    self._handle = _dlopen(self._name, mode)
E   FileNotFoundError: Could not find module 'libopenslide-0.dll'. Try using the full path with constructor syntax.
```

I saw other related issues (https://github.com/openslide/openslide-python/issues/23) that have been fixed replacing line 41 on lowlevel.py with
```
_lib = cdll.LoadLibrary(ctypes.util.find_library("libopenslide-0.dll"))
```

Any idea?

**Comment by simo1427** [comment]
On one installation replacing line 41 with the aforementioned was not enough – Python still gave an error on that line. I tried adding an extra import and then it succeeded:
`from ctypes.uitl import find_library; _lib = cdll.LoadLibrary(find_library("libopenslide-0.dll"))`

**Comment by steven22tom** [comment]
In my situation, I couldn't find "libopenslide-0.dll" in openslide even whole system. And I alse found "libopenslide-0.dll" actually is part of  [libvips](https://github.com/libvips/libvips) .
So I download "libvips", and add the dll path in environment path before import openslide like:
`import os
os.environ['PATH'] = "libvips-bin-path" + ";" + os.environ['PATH']  #libvips-bin-path is where you save the libvips files
import openslide`
It works !

**Comment by Aiosa** [comment]
@steven22tom The required file was missing in the release of the repo you've mentioned. Use [this link instead](https://openslide.org/download/#windows-binaries).

**Comment by thisishardik** [comment]
I have set up my environment variables correctly for the bin folder of openslide but still the same error pops up. Please somebody help me resolve it.
Could not find module 'libopenslide-0.dll' (or one of its dependencies). Try using the full path with constructor syntax.

![image](https://user-images.githubusercontent.com/56413176/114378473-5e5d1600-9ba5-11eb-95cf-9e1efbe8cb0c.png)

**Comment by Aiosa** [comment]
@thisishardik Environmental variables did not work for me as well. Even if you set them up the question is whether they are given to the library which is probably not the case. And also, you probably don't want to manually add such folders to your path, it makes your environment messier: either you run a UNIX-like system, then there are dedicated folders for this, or you run other OS and larger PATH is probably not what you are looking for, especially if only one library needs it.

```
import os
os.add_dll_directory('/path/to/openslide/bin')
import openslide
```

is both more elegant and more portable :)

**Comment by thisishardik** [comment]
> @thisishardik Environmental variables did not work for me as well. Even if you set them up the question is whether they are given to the library which is probably not the case. And also, you probably don't want to manually add such folders to your path, it makes your environment messier: either you run a UNIX-like system, then there are dedicated folders for this, or you run other OS and larger PATH is probably not what you are looking for, especially if only one library needs it.
> 
> ```
> import os
> os.add_dll_directory('/path/to/openslide/bin')
> import openslide
> ```
> 
> is both more elegant and more portable (not in UNIX world, but generally... yes) :)

Thanks man. It actually worked. Even I tried to keep my environment vars list clean though ended up messing it :p. 
Anyways this tweak worked 👍 !!

**Comment by bgilbert** [comment]
https://github.com/openslide/openslide-python/pull/156 addresses this by documenting the need for `os.add_dll_directory()` and adding some hints to the exception text if the DLL can't be found. Thanks for the report and discussion!

**Comment by robertoshea** [comment]
I downloaded the openslide windows binary https://openslide.org/download/. Unzip and the required file is located at "openslide-bin-4.0.0.3-windows-x64/bin/libopenslide-1.dll". Copy it into your openslide bin path
